<head>
       <meta charset="utf-8"/>

        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
        <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no" name="viewport"/>     
        <link rel="icon" href="/web-files/sistema/imagens/favicon-white.png"/>
        <!--        == ESTILOS ==       -->
    
        <link rel="stylesheet" href="/web-files/sistema/css/material-dashboard.css"/>
        <link rel="stylesheet" href="/web-files/sistema/css/material-dashboard.css?v=2.1.0"/>       
        <link rel="stylesheet" href="/web-files/sistema/css/pg-restaurant.css"/>
        <link rel="stylesheet" href="/web-files/sistema/css/demo.css"/>    
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons"/>
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/css/select2.min.css"/>
        <link rel="stylesheet" href="/web-files/sistema/css/style.css"/>
        <script src="https://cdn.ckeditor.com/4.11.3/standard/ckeditor.js"></script>   
        <script src="/web-files/sistema/js/popper.min.js"></script>
        <script src="/web-files/sistema/js/bootstrap-material-design.min.js"></script>
        <script src="/web-files/sistema/js/perfect-scrollbar.jquery.min.js"></script>
        <script src="/web-files/sistema/js/material-dashboard.js" type="text/javascript"></script>
        <script src="/web-files/sistema/js/demo.js"></script>
        <script src="/web-files/sistema/js/jquery.dataTables.min.js"></script>
    <style>
        .select2-selection { overflow: hidden; }
        .select2-selection__rendered { white-space: normal; word-break: break-all; }
    </style>  
  
    <title> PDV</title>
            
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/js/select2.full.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/js/select2.min.js"></script>
</head> 
<script>
    $(document).ready(function(){
        $("#tabela").DataTable({
            dom: "Bfrtip",               
            buttons: [
                "print","pdf","csv"
            ],
            "paging": false,
            "lengthMenu": [
                [10, 25, 50, -1],
                [10, 25, 50, "ALL"]
                ],
            responsive: true               
        });
    });
</script>
<script>
    $(document).ready(function() {
        $(".select").select2({
            width: "resolve" // need to override the changed default
        });
    });
</script>
<?php  foreach ($view_listar_venda AS $listar_venda): ?>
    <div class="content">                
    <div class="container-fluid">             
        <div class="row">
            <div class="col-md-12">
                <div class="card  ">                 
                    <div class="card-header card-header-rose card-header-icon">
                        <div class="card-icon">                             
                           <i class="material-icons">work_outline</i> 
                        </div>
                         <form class='form-check-inline  d-flex justify-content-end pull-right' ><a href='/Admin/index/' type='submit' class='btn btn-sm btn-danger btn-just-icon '><i class='material-icons'>close</i></a></form>                        
                    </div>
                       <form method="post" action="/Itens/incluir_pdv/id_tabela/<?php echo $view_id."/tipo/Venda/caixa/$view_caixa" ;?>'">   
                            <div class="card-body ">
                                <div class="row">             
                                  <div class="col-md-2"> 
                                        <div class="form-group ">
                                            <label  class="">QTD</label>
                                            <input name="quantidade" id="quantidade"type="number" class="form-control"  value="1" >
                                        </div>
                                  </div> 
                                   <div class='col-md-10'> 
                                    <label  class=''>Pesquisa Produto</label>
                                    <div class='form-group '>  
                                       <select tabindex="0"  id='id_produto' name='id_produto'  class='form-control select' onchange='if(this.value != 0) { this.form.submit(); }' style="width:100%"  >
                                            <option  ></option>    
                                            <?php foreach ($view_listar_produto AS $listar_produto):                         
                                                if( $listar_produto['id'] == $listar_itens['id_produto']){ ?>
                                                      <option selected value=' <?php echo $listar_produto['id'] ; ?>' ><?php echo $listar_produto['descricao']." - ".$listar_produto['codigo_barra'] ; ?></option>  <!--  PRECISA MEXER -->
                                                  <?php }else{ ?>
                                                      <option value=' <?php echo $listar_produto['id'].','.$listar_produto['valor_venda'] ; ?> '><?php echo $listar_produto['descricao']." - ".$listar_produto['codigo_barra'] ; ?></option>  <!-- PRECISA MEXER -->
                                            <?php  } endforeach; ?>
                                       </select>
                                    </div>
                                  </div>
                                </div>
                            </div>
                        </form>                          
                      
                           <div class="col-lg-12 col-md-12">
                                    <div class="row">
                                         <div class="card card-header card-header-tabs card-header-rose">
                                            <div class="nav-tabs-navigation">
                                                <div class="nav-tabs-wrapper">
                                                    <span class="nav-tabs-title"></span>
                                                    <ul class="nav nav-tabs" data-tabs="tabs">  
                                                         
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>                                                                                                           
                                        
                                       
                                <div class="card-body">
                                    <div class="tab-content">      
                                        
                                     <div class="tab-pane active" id="contatos">
                                        <div class="row">
                                             <div class="col-md-8">
                                                  <div class="card">
                                                      <div class="card-header card-header-primary card-header-icon">
                                                          <div class="card-icon">
                                                              <i class="material-icons">local_mall</i>
                                                          </div>
                                                          <h4 class="card-title"><b>Produtos</b></h4>                                                         
                                                          
                                                      </div>  
                                                      <div class="card-body">
                                                          <div class="material-datatables">
                                                              <table id="tabela" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                                                                 <thead>                                                                    
                                                                     <tr class="th-table">
                                                                          <th style="font-size:0.9rem;  font-weight: bold;" scope="col">Produto</th>
                                                                          <th style="font-size:0.9rem;  font-weight: bold;" scope="col">Quantidade</th>                                                                          
                                                                          <th style="font-size:0.9rem;  font-weight: bold;" scope="col">Valor Unitario</th>
                                                                          <th style="font-size:0.9rem;  font-weight: bold;" scope="col">Valor Total</th>                                                                          
                                                                          <th style="font-size:0.9rem;  font-weight: bold;" class="disabled-sorting text-right">Ação</th>                                                             
                                                                      </tr>                                                             
                                                                 </thead>    
                                                                 <tfoot>                                                                    
                                                                     <tr class="th-table">
                                                                          <th style="font-size:0.9rem;  font-weight: bold;" scope="col">Produto</th>
                                                                          <th style="font-size:0.9rem;  font-weight: bold;" scope="col">Quantidade</th>                                                                          
                                                                          <th style="font-size:0.9rem;  font-weight: bold;" scope="col">Valor Unitario</th>
                                                                          <th style="font-size:0.9rem;  font-weight: bold;" scope="col">Valor Total</th>                                                                          
                                                                          <th style="font-size:0.9rem;  font-weight: bold;" class="disabled-sorting text-right">Ação</th>                                                             
                                                                      </tr>                                                             
                                                                  </tfoot>                                                                
                                                                 <tbody>                                                  
                                                                         <?php foreach ($view_listar_itens AS $listar_itens): ?>
                                                                     <tr> 
                                                                        <td><?php echo $listar_itens["descricao"]; ?></td>
                                                                        <td scope="row"><?php echo $listar_itens["quantidade"]; ?></td>       
                                                                        <td><?php echo $listar_itens['valor_venda']; $total_venda=$total_venda+($listar_itens['valor_venda']*$listar_itens['quantidade']);?></td>
                                                                        <td scope="row"> <?php echo 'R$' . number_format($listar_itens["quantidade"]*$listar_itens["valor_venda"], 2, ',', '.'); ?> </td>
                                                                        <td class="text-right">                                                                                                                          
                                                                           <form class="form-check-inline" ><a href='/Itens/excluir_pdv/id/<?php echo $listar_itens['id']."/id_tabela/".$listar_venda["id"]."/quantidade/".$listar_itens["quantidade"]."/id_produto/".$listar_itens["id_produto"]."/caixa/".$view_caixa."/tipo/Venda/"; ?>' type="submit" class="btn btn-sm btn-danger btn-just-icon "><i class="material-icons">close</i></a></form>
                                                                        </td>
                                                                     </tr>
                                                                    <?php endforeach; ?>
                                                                  </tbody>
                                                              </table>
                                                      </div>
                                                  </div>
                                              </div>                                             
                                           </div>    
                                            
                                             <div class="col-md-4">
                                               <div class="card">
                                                   <div class="card-header card-header-primary card-header-icon">
                                                       <div class="card-icon">
                                                           <i class="material-icons">payments</i>
                                                       </div>            
                                                       <h4 class="card-title"><b>Finalização</b></h4>
                                                  
                                                   </div>
                                                   <div class="card-body">
                                                       <div class="material-datatables">
                                                          <form class='form-check-inline' action="/Contas/incluir/" method="POST">  
                                                           <div class="row">
                                                               
                                                               <input id='' type='hidden'name='data_vencimento' class='form-control' value="<?php echo date("Y-m-d")?>">
                                                                
                                                                <input id='' type='hidden'name='id_filial'  required='true'value='<?php echo $view_user_dados['id_filial'] ?>'>
                                                                <input id='' type='hidden'name='id_status'  required='true'value='1'>
                                                                <input id='' type='hidden'name='id_colaborador'  required='true'value='<?php echo $view_user_dados['id_colaborador'] ?>'>
                                                                <input id='' type='hidden'name='id_conta_bancaria'  required='true'value='1'>
                                                                <input id='' type='hidden'name='id'  required='true'value='<?php echo $listar_venda['id'] ?>'>
                                                                <input id='' type='hidden'name='id_tabela'  required='true'value='<?php echo $listar_venda['id'] ?>'>

                                                                <input id='' type='hidden'name='caixa'  required='true'value='<?php echo $view_caixa; ?>'>
                                                                <input id='' type='hidden'name='tabela'  required='true'value='Venda'>
                                                                <input id='' type='hidden' name='tipo'  required='true'value='Receita<?php //echo $listar_venda['tipo']; ?>'>
                                                                <input id='' type='hidden' name='tipo2'  required='true'value='Pdv'>
                                                                
                                                                <div class='col-md-12'> 
                                                                    <label  class=''>Pesquisa Cliente</label>
                                                                    <div class='form-group '>  
                                                                       <select id='id_cliente' name='id_pessoa' class='form-control select' required='true' autocorrect='off' autocomplete='off' style="width:100%">
                                                                      <?php foreach ($view_listar_cliente AS $listar_cliente):                        
                                                                          if( $listar_cliente['id'] == $listar_venda['id_cliente']){ ?>
                                                                                <option selected='true' value=' <?php echo $listar_cliente['id'] ; ?>' ><?php echo $listar_cliente['nome'] ; ?></option>  <!--  PRECISA MEXER -->
                                                                            <?php }else{ ?>
                                                                                <option value=' <?php echo $listar_cliente['id'] ; ?> '><?php echo $listar_cliente['nome'] ; ?></option>  <!-- PRECISA MEXER -->
                                                                      <?php  } endforeach; ?>
                                                                      </select>  
                                                                    </div>
                                                                </div>
                                                               
                                                               
                                                               <div class='col-md-6'> 
                                                                    <label  class=''>Tipo Pagamento</label>
                                                                    <div class='form-group '>  
                                                                      <select id='id_tipo_documento' name='id_tipo_documento' class='form-control select' required='true' autocorrect='off' autocomplete='off' style="width:100%">
                                                                    <?php foreach ($view_listar_tipo_documento AS $listar_tipo_documento):                        
                                                                        if( $listar_tipo_documento['id'] == $listar_venda['id_tipo_documento']){ ?>
                                                                              <option selected='true' value=' <?php echo $listar_tipo_documento['id'] ; ?>' ><?php echo $listar_tipo_documento['descricao'] ; ?></option>  <!--  PRECISA MEXER -->
                                                                          <?php }else{ ?>
                                                                              <option value=' <?php echo $listar_tipo_documento['id'] ; ?> '><?php echo $listar_tipo_documento['descricao'] ; ?></option>  <!-- PRECISA MEXER -->
                                                                    <?php  } endforeach; ?>
                                                               </select> 
                                                                    </div>
                                                                </div>
                                                               <div class='col-md-6'> 
                                                                    <label  class=''>Forma Pagamento</label>
                                                                    <div class='form-group '>  
                                                                        <select id='id_tipo_pagamento' name='id_tipo_pagamento' class='form-control select' required='true' autocorrect='off' autocomplete='off' style="width:100%">
                                                                            <?php foreach ($view_listar_tipo_pagamento AS $listar_tipo_pagamento):                        
                                                                                if( $listar_tipo_pagamento['id'] == $listar_venda['id_tipo_pagamento']){ ?>
                                                                                      <option selected='true' value=' <?php echo $listar_tipo_pagamento['id'] ; ?>' ><?php echo $listar_tipo_pagamento['descricao'] ; ?></option>  <!--  PRECISA MEXER -->
                                                                                  <?php }else{ ?>
                                                                                      <option value=' <?php echo $listar_tipo_pagamento['id'] ; ?> '><?php echo $listar_tipo_pagamento['descricao'] ; ?></option>  <!-- PRECISA MEXER -->
                                                                            <?php  } endforeach; ?>
                                                                       </select>   
                                                                    </div>
                                                                </div>
                                                               
                                                               <div class="col-md-6"> 
                                                                <div class="form-group ">
                                                                    <label  class="">Pago</label>
                                                                    <input type="number" id="valor_entrada" name="valor_entrada"class="form-control" >
                                                                </div>
                                                                </div>
                                                                 <div class="col-md-6"> 
                                                                      <div class="form-group ">
                                                                          <label  class="">Troco</label>
                                                                          <input type="text" onclick="teste()"id="valor_troco" name="valor_troco"class="form-control" >
                                                                      </div>
                                                                </div>
                                                                 <div class="col-md-12"> 
                                                                    <button  type="submit" name="finalizar" id="finalizar"class='btn btn-sm btn-success' >FINALIZAR (F2)</button>  
                                                                    <a  href='/Cupom/nf_termica/id/<?php echo $listar_venda["id"]."/pago/$total_venda/" ?>' class='btn btn-sm btn-info '>CUPOM</a>                                                          
                                                                    <a  href='/Itens/excluir_pdv/id/<?php echo $listar_itens['id']."/id_tabela/".$listar_venda["id"]; ?>' class='btn btn-sm btn-danger  '>CANCELAR (F3)</a>
                                                                </div>
                                                                <input type='hidden'  id="valor_total" name='valor_total' class='form-control' required='true' value='<?php echo $total_venda;?>'>     
                                                              
                                                                </div>
                                                            </form>
                                                            </div>
                                                            
                                                       </div>
                                                   </div>
                                                   <h1>  <?php echo 'R$' . number_format($total_venda, 2, ',', '.'); ?></h1>
                                               </div>           
                                            </div>
                                            
                                        </div>
                                      </div>
                                    </div>
                                </div>  
                               
                            </div>
                            <div class="row">
                                <div class="card card-header card-header-tabs card-header-rose">
                                    <div class="nav-tabs-navigation">
                                       <div class="nav-tabs-wrapper">
                                           <span class="nav-tabs-title"></span>
                                           <ul class="nav nav-tabs" data-tabs="tabs">  
                                                <li class="nav-item">
                                                    <a class="nav-link" href="#financeiro" data-toggle="tab">
                                                        <i class="material-icons">request_quote</i> <?php echo 'R$' . number_format($total_venda, 2, ',', '.'); ?>
                                                        <div class="ripple-container"></div>
                                                    </a>
                                                </li>
                                           </ul>
                                        </div>
                                   </div>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                
                
               </div>
            </div>
        </div>            
        </div>   
        <?php  endforeach; ?>
 <script>              
  
        $("#valor_entrada").keyup(function(){
        var valor_entrada = $("#valor_entrada").val();
        var valor_total = $("#valor_total").val(); 
        var valor_troco = valor_entrada-valor_total;
     
        $("#valor_troco").val(valor_troco.toLocaleString('us', {minimumFractionDigits: 2, maximumFractionDigits: 2}));
       
      });
      
      $(window).on("keyup", function(event) {
    if (event.keyCode == 113) {
   
      $("#finalizar").trigger("click");
   
    }
});


</script> 