<?php 

           // require_once 'inicio.phtml';          

            if(empty($view_id)){ ?>

        <div class='content'>

                <div class='container-fluid'>

                    <div class='row'>

                        <div class='col-md-12'>

                            <div class='card '>

                                <div class='card-header card-header-rose card-header-icon'>

                                    <div class='card-icon'>

                                        <i class='material-icons'>add_shopping_cart</i>

                                    </div>

                                    <h4 class='card-title'>Lançamento <?php echo $view_tipo;?> </h4>

                                </div>

                               <form form enctype='multipart/form-data'  method="post" action='/Venda/incluir/tipo/<?php echo $view_tipo; ?>'> <!-- PRECISA MEXER -->

                                    <div class='card-body '>

                                        <div class='row'>

                                                        <input id='' type='hidden'name='id'  required='true'value='<?php echo $listar_venda['id'] ?>'>

                                                        <input id='' type='hidden'name='id_fornecedor'  required='true'value='0'>

                                                        

                                                     <div class='col-md-2'> 

                                                            <div class='form-group '>

                                                               <label  class='bmd-label-floating'>Filial</label>

                                                               <select id='id_filial' name='id_filial' class='form-control select ' style="width: 100%"required='true' autocorrect='off' autocomplete='off'>

                                                                    <?php foreach ($view_listar_filial AS $listar_filial):                        

                                                                        if( $listar_filial['id'] == $listar_venda['id_filial']){ ?>

                                                                              <option selected='true' value=' <?php echo $listar_filial['id'] ; ?>' ><?php echo $listar_filial['nome_fantasia'] ; ?></option>  <!--  PRECISA MEXER -->

                                                                          <?php }else{ ?>

                                                                              <option value=' <?php echo $listar_filial['id'] ; ?> '><?php echo $listar_filial['nome_fantasia'] ; ?></option>  <!-- PRECISA MEXER -->

                                                                    <?php  } endforeach; ?>

                                                               </select> 

                                                            </div>

                                                        </div>

                                                        <div class='col-md-5'> 

                                                            <div class='form-group '>

                                                               <label  class='bmd-label-floating'> <?php if($view_tipo=="Receita"){ echo "Cliente";}else{ echo"Fornecedor"; } ?></label>

                                                               <select id='id_cliente' name='id_pessoa' class='form-control select ' style="width: 100%"required='true' autocorrect='off' autocomplete='off'>

                                                                    <?php foreach ($view_listar_cliente AS $listar_cliente):                        

                                                                        if( $listar_cliente['id'] == $listar_venda['id_cliente']){ ?>

                                                                              <option selected='true' value=' <?php echo $listar_cliente['id'] ; ?>' ><?php echo $listar_cliente['nome']." ".$listar_cliente['cpf'] ; ?></option>  <!--  PRECISA MEXER -->

                                                                          <?php }else{ ?>

                                                                              <option value=' <?php echo $listar_cliente['id'] ; ?> '><?php echo $listar_cliente['nome']." ".$listar_cliente['cpf'] ; ?></option>  <!-- PRECISA MEXER -->

                                                                    <?php  } endforeach; ?>

                                                               </select> 

                                                            </div>

                                                         </div>

                                                        <div class='col-md-5'> 

                                                            <div class='form-group '>

                                                               <label  class='bmd-label-floating'>Colaborador</label>

                                                               <select id='id_colaborador' name='id_colaborador' class=' select form-control' style="width: 100%"required='true' autocorrect='off' autocomplete='off'>

                                                                    <?php foreach ($view_listar_colaborador AS $listar_colaborador):                        

                                                                        if( $listar_colaborador['id'] == $listar_venda['id_colaborador']){ ?>

                                                                              <option selected='true' value=' <?php echo $listar_colaborador['id'] ; ?>' ><?php echo $listar_colaborador['nome'] ; ?></option>  <!--  PRECISA MEXER -->

                                                                          <?php }else{ ?>

                                                                              <option value=' <?php echo $listar_colaborador['id'] ; ?> '><?php echo $listar_colaborador['nome'] ; ?></option>  <!-- PRECISA MEXER -->

                                                                    <?php  } endforeach; ?>

                                                               </select> 

                                                            </div>

                                                         </div>

                                                        

                                                        

                                                        <div class='col-md-3'> 

                                                            <div class='form-group '>

                                                               <label  class='bmd-label-floating'>Tipo de Documento</label>

                                                               <select id='id_tipo_documento' name='id_tipo_documento' class=' select form-control' required='true' autocorrect='off' autocomplete='off'>

                                                                    <?php foreach ($view_listar_tipo_documento AS $listar_tipo_documento):                        

                                                                        if( $listar_tipo_documento['id'] == $listar_venda['id_tipo_documento']){ ?>

                                                                              <option selected='true' value=' <?php echo $listar_tipo_documento['id'] ; ?>' ><?php echo $listar_tipo_documento['descricao'] ; ?></option>  <!--  PRECISA MEXER -->

                                                                          <?php }else{ ?>

                                                                              <option value=' <?php echo $listar_tipo_documento['id'] ; ?> '><?php echo $listar_tipo_documento['descricao'] ; ?></option>  <!-- PRECISA MEXER -->

                                                                    <?php  } endforeach; ?>

                                                               </select> 

                                                            </div>

                                                         </div>

                                                        

                                                        

                                                        <div class='col-md-3'> 

                                                            <div class='form-group '>
 
                                                               <label  class='bmd-label-floating'>Forma de Pagamento</label>

                                                               <select id='id_tipo_pagamentos' name='id_tipo_pagamento' class=' select form-control' required='true'style="width: 100%" autocorrect='off' autocomplete='off'>

                                                                    <?php foreach ($view_listar_tipo_pagamento AS $listar_tipo_pagamento):                        

                                                                        if( $listar_tipo_pagamento['id'] == $listar_venda['id_tipo_pagamento']){ ?>

                                                                              <option selected='true' value=' <?php echo $listar_tipo_pagamento['id'] ; ?>' ><?php echo $listar_tipo_pagamento['descricao']."  ".$listar_tipo_pagamento['juros'] ;  ; ?></option>  <!--  PRECISA MEXER -->

                                                                          <?php }else{ ?>

                                                                              <option value=' <?php echo $listar_tipo_pagamento['id'] ; ?> '><?php echo $listar_tipo_pagamento['descricao']."  ".$listar_tipo_pagamento['juros'] ;  ; ?></option>  <!-- PRECISA MEXER -->

                                                                    <?php  } endforeach; ?>

                                                               </select> 

                                                            </div>

                                                         </div>

                                                        <div class='col-md-2'> 

                                                            <div class='form-group '>

                                                               <label  class='bmd-label-floating'>Plano de Contas</label>

                                                               <select id='id_plano_contas' name='id_plano_contas' class=' select form-control' required='true' style="width: 100%"autocorrect='off' autocomplete='off'>

                                                                    <?php foreach ($view_listar_plano_conta AS $listar_plano_conta):                        

                                                                        if( $listar_plano_contas['id'] == $listar_venda['id_plano_conta']){ ?>

                                                                              <option selected='true' value=' <?php echo $listar_plano_conta['id'] ; ?>' ><?php echo $listar_plano_conta['descricao'] ; ?></option>  <!--  PRECISA MEXER -->

                                                                          <?php }else{ ?>

                                                                              <option value=' <?php echo $listar_plano_conta['id'] ; ?> '><?php echo $listar_plano_conta['descricao'] ; ?></option>  <!-- PRECISA MEXER -->

                                                                    <?php  } endforeach; ?>

                                                               </select> 

                                                            </div>

                                                         </div>

                                                        

                                                        <div class='col-md-2'> 

                                                            <div class='form-group '>

                                                               <label  class='bmd-label-floating'>Conta/Caixa</label>

                                                               <select id='id_conta_bancaria' name='id_conta_bancaria' class=' select form-control' required='true' autocorrect='off' autocomplete='off'>

                                                                    <?php foreach ($view_listar_conta_bancaria AS $listar_conta_bancaria):                        

                                                                        if( $listar_conta_bancaria['id'] == $listar_venda['id_conta_bancaria']){ ?>

                                                                              <option selected='true' value=' <?php echo $listar_conta_bancaria['id'] ; ?>' ><?php echo $listar_conta_bancaria['descricao'] ; ?></option>  <!--  PRECISA MEXER -->

                                                                          <?php }else{ ?>

                                                                              <option value=' <?php echo $listar_conta_bancaria['id'] ; ?> '><?php echo $listar_conta_bancaria['descricao'] ; ?></option>  <!-- PRECISA MEXER -->

                                                                    <?php  } endforeach; ?>

                                                               </select> 

                                                            </div>

                                                         </div>

                                                        <div class='col-md-2'> 

                                                            <div class='form-group '>

                                                                <label  class='bmd-label-floating'>Código</label>

                                                                <input id='' type='text'name='codigo' class='form-control' required='true' value=''>

                                                            </div>

                                                        </div>

                                                        

                                        </div>

                                        <div class="row">

                                                        <div class='card-footer text-right'>

                                           <button type='submit' name='' class='btn btn-rose' required=''>Salvar</button>

                                       </div>

                                    </div>

                                </div>

                           </form>

                       </div>

                   </div>

                </div>

            </div>

        </div>

<br><br>                                      

    <?php

        }else{

            foreach ($view_listar_venda AS $listar_venda):

     ?>

    

        <div class='content'>

                <div class='container-fluid'>

                    <div class='row'>

                        <div class='col-md-12'>

                            <div class='card '>

                                <div class='card-header card-header-rose card-header-icon'>

                                    <div class='card-icon'>

                                        <i class='material-icons'>add_shopping_cart</i>

                                    </div>

                                    <h4 class='card-title'>Lançamento <?php echo $view_tipo." - ". $listar_venda["id"]; ?></h4>

                                </div>

                               <form form enctype='multipart/form-data' method='post' action='/Contas/incluir/'> <!-- PRECISA MEXER -->

                                    <div class='card-body '>

                                         <div class='row'>

                                                        <input id='' type='hidden'name='id'  required='true'value='<?php echo $listar_venda['id'] ?>'>

                                                        <input id='' type='hidden'name='id_tabela'  required='true'value='<?php echo $listar_venda['id'] ?>'>

                                                        <input id='' type='hidden'name='tabela'  required='true'value='Venda'>

                                                        <input id='' type='hidden' name='tipo'  required='true'value='<?php echo $listar_venda['tipo']; ?>'>

                                                        <div class='col-md-2'> 

                                                            <div class='form-group '>

                                                               <label  class='bmd-label-floating'>Filial</label>

                                                               <select id='id_filial' name='id_filial' class='form-control select 'style="width: 100%" required='true' autocorrect='off' autocomplete='off'>

                                                                    <?php foreach ($view_listar_filial AS $listar_filial):                        

                                                                        if( $listar_filial['id'] == $listar_venda['id_filial']){ ?>

                                                                              <option selected='true' value=' <?php echo $listar_filial['id'] ; ?>' ><?php echo $listar_filial['nome_fantasia'] ; ?></option>  <!--  PRECISA MEXER -->

                                                                          <?php }else{ ?>

                                                                              <option value=' <?php echo $listar_filial['id'] ; ?> '><?php echo $listar_filial['nome_fantasia'] ; ?></option>  <!-- PRECISA MEXER -->

                                                                    <?php  } endforeach; ?>

                                                               </select> 

                                                            </div>

                                                         </div>

                                                        

                                                        <div class='col-md-5'> 

                                                            <div class='form-group '>

                                                             <label  class='bmd-label-floating'> <?php if($view_tipo=="Receita"){ echo "Cliente";}else{ echo"Fornecedor "; } ?></label>

                                                               <select id='id_cliente' name='id_pessoa' class='form-control select 'style="width: 100%" required='true' autocorrect='off' autocomplete='off'>

                                                                    <?php foreach ($view_listar_cliente AS $listar_cliente):           
                                                                      

                                                                        if( $listar_cliente['id'] == $listar_venda['id_cliente'] OR $listar_cliente['id'] == $listar_venda['id_fornecedor']  ){ ?>

                                                                              <option selected='true' value=' <?php echo $listar_cliente['id'] ; ?>' ><?php echo $listar_cliente['nome']." ".$listar_cliente['cpf'] ; ?></option>  <!--  PRECISA MEXER -->

                                                                          <?php }else{ ?>

                                                                              <option value=' <?php echo $listar_cliente['id'] ; ?> '><?php echo $listar_cliente['nome']." ".$listar_cliente['cpf'] ; ?></option>  <!-- PRECISA MEXER -->

                                                                    <?php  } endforeach; ?>

                                                               </select> 

                                                            </div>

                                                         </div>

                                                        <div class='col-md-5'> 

                                                            <div class='form-group '> 

                                                               <label  class='bmd-label-floating'>Colaborador</label>

                                                               <select id='id_colaborador' name='id_colaborador' class=' select form-control'style="width: 100%" required='true' autocorrect='off' autocomplete='off'>

                                                                    <?php foreach ($view_listar_colaborador AS $listar_colaborador):                        

                                                                        if( $listar_colaborador['id'] == $listar_venda['id_colaborador']){ ?>

                                                                              <option selected='true' value=' <?php echo $listar_colaborador['id'] ; ?>' ><?php echo $listar_colaborador['nome'] ; ?></option>  <!--  PRECISA MEXER -->

                                                                          <?php }else{ ?>

                                                                              <option value=' <?php echo $listar_colaborador['id'] ; ?> '><?php echo $listar_colaborador['nome'] ; ?></option>  <!-- PRECISA MEXER -->

                                                                    <?php  } endforeach; ?>

                                                               </select> 

                                                            </div>

                                                         </div>

                                                        

                                                        

                                                        <div class='col-md-3'> 

                                                            <div class='form-group '>

                                                               <label  class='bmd-label-floating'>Tipo de Documento</label>

                                                               <select id='id_tipo_documento' name='id_tipo_documento' class=' select form-control' required='true'style="width: 100%"  autocorrect='off' autocomplete='off'>

                                                                    <?php foreach ($view_listar_tipo_documento AS $listar_tipo_documento):                        

                                                                        if( $listar_tipo_documento['id'] == $listar_venda['id_tipo_documento']){ ?>

                                                                              <option selected='true' value=' <?php echo $listar_tipo_documento['id'] ; ?>' ><?php echo $listar_tipo_documento['descricao'] ; ?></option>  <!--  PRECISA MEXER -->

                                                                          <?php }else{ ?>

                                                                              <option value=' <?php echo $listar_tipo_documento['id'] ; ?> '><?php echo $listar_tipo_documento['descricao'] ; ?></option>  <!-- PRECISA MEXER -->

                                                                    <?php  } endforeach; ?>

                                                               </select> 

                                                            </div>

                                                         </div>

                                                        

                                                         <div class='col-md-3'> 

                                                            <div class='form-group '>

                                                               <label  class='bmd-label-floating'>Forma de Pagamento</label>

                                                               <select id="id_tipo_pagamento2" name='id_tipo_pagamento' style="width: 100%" class="form-control select">

                                                                   <?php foreach ($view_listar_tipo_pagamento AS $listar_tipo_pagamento):                        

                                                                        if( $listar_tipo_pagamento['id'] == $listar_venda['id_tipo_pagamento']){ ?>

                                                                              <option selected='true' value=' <?php echo $listar_tipo_pagamento['id'] ; ?>' ><?php echo $listar_tipo_pagamento['descricao']."  ".$listar_tipo_pagamento['juros'] ; ?></option>  <!--  PRECISA MEXER -->

                                                                          <?php }else{ ?>

                                                                              <option value=' <?php echo $listar_tipo_pagamento['id'] ; ?> '><?php echo $listar_tipo_pagamento['descricao'] ."  ".$listar_tipo_pagamento['juros'] ; ?></option>  <!-- PRECISA MEXER -->

                                                                    <?php  } endforeach; ?>

                                                                </select>

                                                            </div>

                                                         </div>

                                                        <div class='col-md-3'> 

                                                            <div class='form-group '>

                                                               <label  class='bmd-label-floating'>Conta/Caixa</label>

                                                               <select id='id_conta_bancaria' name='id_conta_bancaria' class=' select form-control' style="width: 100%"required='true' autocorrect='off' autocomplete='off'>

                                                                    <?php foreach ($view_listar_conta_bancaria AS $listar_conta_bancaria):                        

                                                                        if( $listar_conta_bancaria['id'] == $listar_venda['id_conta_bancaria']){ ?>

                                                                              <option selected='true' value=' <?php echo $listar_conta_bancaria['id'] ; ?>' ><?php echo $listar_conta_bancaria['descricao'] ; ?></option>  <!--  PRECISA MEXER -->

                                                                          <?php }else{ ?>

                                                                              <option value=' <?php echo $listar_conta_bancaria['id'] ; ?> '><?php echo $listar_conta_bancaria['descricao'] ; ?></option>  <!-- PRECISA MEXER -->

                                                                    <?php  } endforeach; ?>

                                                               </select> 

                                                            </div>

                                                         </div>

                                                        <div class='col-md-3'> 

                                                            <div class='form-group '>

                                                               <label  class='bmd-label-floating'>Plano de Contas</label>

                                                               <select id='id_tipo_pagamento' name='id_plano_contas'style="width: 100%" class=' select form-control' required='true' autocorrect='off' autocomplete='off'>

                                                                    <?php foreach ($view_listar_plano_conta AS $listar_plano_conta):                        

                                                                        if( $listar_plano_contas['id'] == $listar_venda['id_plano_conta']){ ?>

                                                                              <option selected='true' value=' <?php echo $listar_plano_conta['id'] ; ?>' ><?php echo $listar_plano_conta['descricao'] ; ?></option>  <!--  PRECISA MEXER -->

                                                                          <?php }else{ ?>

                                                                              <option value=' <?php echo $listar_plano_conta['id'] ; ?> '><?php echo $listar_plano_conta['descricao'] ; ?></option>  <!-- PRECISA MEXER -->

                                                                    <?php  } endforeach; ?>

                                                               </select> 

                                                            </div>

                                                         </div>

                                                        

                                                        <div class='col-md-3'> 

                                                            <div class='form-group '>

                                                               <label  class='bmd-label-floating'>Status</label>

                                                               <select id='id_status' name='id_status'style="width: 100%" class=' select form-control' required='true' autocorrect='off' autocomplete='off'>

                                                                    <?php foreach ($view_listar_status AS $listar_status):                        

                                                                        if( $listar_status['id'] == $listar_venda['id_status']){ ?>

                                                                              <option selected='true' value=' <?php echo $listar_status['id'] ; ?>' ><?php echo $listar_status['descricao'] ; ?></option>  <!--  PRECISA MEXER -->

                                                                          <?php }else{ ?>

                                                                              <option value=' <?php echo $listar_status['id'] ; ?> '><?php echo $listar_status['descricao'] ; ?></option>  <!-- PRECISA MEXER -->

                                                                    <?php  } endforeach; ?>

                                                               </select> 

                                                            </div>

                                                         </div>

                                                        <div class='col-md-2'> 

                                                            <div class='form-group '>

                                                                <label  class='bmd-label-floating'>Valor de Entrada</label> 

                                                                <input id='' type='number'name='valor_entrada' class='form-control' required='true' value='<?php echo $listar_venda['valor_entrada'] ; ?>'>

                                                            </div>

                                                        </div>
                                                        
                                                        <div class='col-md-2'> 

                                                            <div class='form-group '>

                                                                <label  class='bmd-label-floating'>Valor de Desconto (%)</label> 

                                                                <input id='number' type='number'name='valor_desconto' class='form-control'  value='<?php echo $listar_venda['valor_desconto'] ; ?>'>

                                                            </div>

                                                        </div>

                                                        <div class='col-md-2'> 

                                                            <div class='form-group '>

                                                                <label  class='bmd-label-floating'>Código</label>

                                                                <input id='' type='text'name='codigo' class='form-control' required='true' value='<?php echo $listar_venda['codigo'] ; ?>'>

                                                            </div>

                                                        </div>

                                                        

                                                        <div class='col-md-3'>  

                                                            <div class='form-group '>

                                                                <label  class='bmd-label-floating'>Data de Vencimento</label>

                                                                <input id='' type='date'name='data_vencimento' class='form-control' required='true' value="<?php echo $listar_venda['data_vencimento'] ; ?>">

                                                            </div>

                                                        </div>

                                                            <div class="ol-lg-12 col-md-12">

                                                                <div class="card">

                                                                    <div class="card-header card-header-tabs card-header-rose">

                                                                        <div class="nav-tabs-navigation">

                                                                            <div class="nav-tabs-wrapper">

                                                                                <span class="nav-tabs-title"></span>

                                                                                <ul class="nav nav-tabs" data-tabs="tabs">



                                                                                    <li class="nav-item ">

                                                                                        <a class="nav-link " href="#produto" data-toggle="tab">

                                                                                            <i class="material-icons">shopping_basket</i> Produto

                                                                                            <div class="ripple-container"></div>

                                                                                        </a>

                                                                                    </li>

                                                                                    <li class="nav-item">

                                                                                        <a class="nav-link active" href="#servicos" data-toggle="tab">

                                                                                            <i class="material-icons">settings_input_composite</i> Serviços

                                                                                            <div class="ripple-container"></div>

                                                                                        </a>

                                                                                    </li> 

                                                                                    <li class="nav-item">

                                                                                        <a class="nav-link" href="#outros" data-toggle="tab">

                                                                                            <i class="material-icons">library_books</i> Outros

                                                                                            <div class="ripple-container"></div>

                                                                                        </a>

                                                                                    </li> 

                                                                                </ul>

                                                                            </div>

                                                                        </div>

                                                                    </div>                                       



                                                                    <div class="card-body">

                                                                        <div class="tab-content">    

                                                                            <div class="tab-pane " id="produto">

                                                                               <div class="row">

                                                                                    <div class="col-md-12">

                                                                                        <div class="card">

                                                                                             

                                                                                            <div class="card-header card-header-primary card-header-icon row">  

                                                                                                <a href='/Itens/form/id_tabela/<?php echo $listar_venda["id"]."/tabela/Produto/tipo/".$listar_venda["tipo"] ;?>' type='submit' class='btn btn-md btn-rose pull-right  '><i class='material-icons '>add_circle_outline</i></a>

                                                                                            </div> 

                                                                                            <div class="card-body">                                                                        

                                                                                                <div class='material-datatables'>

                                                                                                    <table id='tabela' class='table table-striped table-no-bordered table-hover' cellspacing='0' width='100%' style='width:100%'>

                                                                                                        <thead>

                                                                                                            <tr> 

                                                                                                            <th scope='col'>Produto</th>

                                                                                                            <th scope='col'>Descrição</th> 

                                                                                                            <th scope='col'>Quantidade</th>

                                                                                                            <th scope='col'>Valor do Iten</th>
                                                                                                            <th scope='col'>Valor Total</th>

                                                                                                            <th scope='col'>Valor de Desconto</th>

                                                                                                            <!--<th scope='col'>Valor_compra</th>-->

                                                                                                            <th scope='col' class="text-right">Ação</th>

                                                                                                        </tr>

                                                                                                        </thead>

                                                                                                     <tfoot>

                                                                                                        <tr> 

                                                                                                            <th scope='col'>Produto</th>

                                                                                                            <th scope='col'>Descricao</th>

                                                                                                            <th scope='col'>Quantidade</th>

                                                                                                            <th scope='col'>Valor do Iten</th>
                                                                                                            <th scope='col'>Valor Total</th>

                                                                                                            <th scope='col'>Valor de Desconto</th>

                                                                                                            <!--<th scope='col'>valor_compra</th>-->

                                                                                                            <th scope='col' class="text-right">Ação</th>



                                                                                                        </tr>

                                                                                                    </tfoot>

                                                                                                    <tbody>

                                                                                                                <?php foreach ($view_listar_itens AS $listar_itens):  ?>                                              

                                                                                                                <tr> 



                                                                                                                    <td><?php echo $listar_itens['id_produto']; ?></td>

                                                                                                                    <td><?php echo $listar_itens['descricao']; ?></td>

                                                                                                                    <td><?php echo $listar_itens['quantidade']; ?></td>

                                                                                                                    <td><?php echo $listar_itens['valor_venda']; ?></td>
                                                                                                                    <td><?php  $total_venda=$total_venda+($listar_itens['valor_venda']*$listar_itens['quantidade']);echo $total_venda; ?></td>
                                                                                                                    <td><?php echo $listar_itens['valor_desconto']; ?></td>

                                                                                                                    <td class='text-right'>                                                   

                                                                                                                        <form class='form-check-inline'><a onclick="return confirm('Tem Certeza que deseja EXCLUIR ?');"   href='/Itens/excluir/id/<?php echo $listar_itens['id']."/id_tabela/".$listar_venda["id"]."/quantidade/".$listar_itens['quantidade']."/id_iten/".$listar_itens['id_produto']."/"; ?>' class='btn btn-sm btn-danger btn-just-icon '><i class='material-icons'>close</i></a></form>

                                                                                                                    </td>                    

                                                                                                                 </tr>

                                                                                                            <?php endforeach; ?> 

                                                                                                        </tbody>

                                                                                                    </table>

                                                                                                </div>

                                                                                            </div>

                                                                                        </div>                                             

                                                                                  </div>                                                                                       

                                                                               </div>

                                                                            </div>

                                                                            <div class="tab-pane active" id="servicos">

                                                                                <div class="row">
 
                                                                                    <div class="col-md-12">

                                                                                        <div class="card">

                                                                                            <div class="card-header card-header-primary card-header-icon">

                                                                                                <a href='/Itens/form/id_tabela/<?php echo $listar_venda["id"]."/tabela/Servico/tipo/".$listar_venda["tipo"] ;?>' type='submit' class='btn btn-md btn-rose pull-right  '><i class='material-icons '>add_circle_outline</i></a>

                                                                                            </div> 



                                                                                            <div class="card-body">                                                                        

                                                                                                <div class='material-datatables'>

                                                                                                    <table id='tabela1' class='table table-striped table-no-bordered table-hover' cellspacing='0' width='100%' style='width:100%'><thead>

                                                                                                     

                                                                                                            <tr> 

                                                                                                            <th scope='col'>Produto</th>

                                                                                                            <th scope='col'>Descrição</th>

                                                                                                            <th scope='col'>Quantidade</th>

                                                                                                            <th scope='col'>Valor do Iten</th>
                                                                                                            <th scope='col'>Valor Total</th>

                                                                                                            <th scope='col'>Valor de Desconto</th>

                                                                                                            <!--<th scope='col'>Valor_compra</th>-->

                                                                                                            <th scope='col' class="text-right">Ação</th>

                                                                                                        </tr>

                                                                                                        </thead>

                                                                                                     <tfoot>

                                                                                                        <tr> 

                                                                                                            <th scope='col'>Produto</th>

                                                                                                            <th scope='col'>Descricao</th>

                                                                                                            <th scope='col'>Quantidade</th>

                                                                                                            <th scope='col'>Valor do Iten</th>
                                                                                                            <th scope='col'>Valor Total</th>

                                                                                                            <th scope='col'>Valor de Desconto</th>

                                                                                                            <!--<th scope='col'>valor_compra</th>-->

                                                                                                            <th scope='col' class="text-right">Ação</th>



                                                                                                        </tr>

                                                                                                    </tfoot>

                                                                                                    <tbody>

                                                                                                                <?php foreach ($view_listar_servico AS $listar_servico):  ?>                                              

                                                                                                                <tr> 



                                                                                                                    <td><?php echo $listar_servico['id_produto']; ?></td>

                                                                                                                    <td><?php echo $listar_servico['descricao']; ?></td>

                                                                                                                    <td><?php echo $listar_servico['quantidade']; ?></td>

                                                                                                                    <td><?php echo $listar_servico['valor_venda']; ?></td>
                                                                                                                    <td><?php  $total_servico=$total_servico+($listar_servico['valor_venda']*$listar_servico['quantidade']);echo $total_servico; ?></td>

                                                                                                                    <td><?php echo $listar_servico['valor_desconto']; ?></td>

                                                                                                                    <td class='text-right'>                                                   

                                                                                                                        <form class='form-check-inline'><a onclick="return confirm('Tem Certeza que deseja EXCLUIR ?');"   href='/Itens/excluir/id/<?php echo $listar_servico['id']."/id_tabela/".$listar_venda["id"]; ?>' class='btn btn-sm btn-danger btn-just-icon '><i class='material-icons'>close</i></a></form>

                                                                                                                    </td>                    

                                                                                                                 </tr>

                                                                                                            <?php endforeach; ?> 

                                                                                                        </tbody>

                                                                                                    </table>

                                                                                                </div>

                                                                                            </div>

                                                                                        </div>                                             

                                                                                   </div>                                                                                       

                                                                                </div>

                                                                            </div>     

                                                                            

                                                                            

                                                                            <div class="tab-pane " id="outros">

                                                                                <div class="row">

                                                                                    <div class="col-md-12">

                                                                                        <div class="card">

                                                                                            <div class="card-header card-header-primary card-header-icon">

                                                                                                <a href='/Itens/form/id_tabela/<?php echo $listar_venda["id"]."/tabela/Outros/tipo/".$listar_venda["tipo"] ;?>' type='submit' class='btn btn-md btn-rose pull-right  '><i class='material-icons '>add_circle_outline</i></a>

                                                                                            </div> 



                                                                                            <div class="card-body">                                                                        

                                                                                                <div class='material-datatables'>

                                                                                                     <table id='tabela2' class='table table-striped table-no-bordered table-hover' cellspacing='0' width='100%' style='width:100%'>
                                                                                                       
                                                                                                       <thead>

                                                                                                        

                                                                                                            <tr> 

                                                                                                            <th scope='col'>Produto</th>

                                                                                                            <th scope='col'>Descrição</th>

                                                                                                            <th scope='col'>Quantidade</th>

                                                                                                            <th scope='col'>Valor do Iten</th>
                                                                                                            <th scope='col'>Valor Total</th>

                                                                                                            <th scope='col'>Valor de Desconto</th>

                                                                                                            <!--<th scope='col'>Valor_compra</th>-->

                                                                                                            <th scope='col' class="text-right">Ação</th>

                                                                                                        </tr>

                                                                                                        </thead>

                                                                                                     <tfoot>

                                                                                                        <tr> 

                                                                                                            <th scope='col'>Produto</th>

                                                                                                            <th scope='col'>Descricao</th>

                                                                                                            <th scope='col'>Quantidade</th>

                                                                                                           <th scope='col'>Valor do Iten</th>
                                                                                                            <th scope='col'>Valor Total</th>

                                                                                                            <th scope='col'>Valor de Desconto</th>

                                                                                                            <!--<th scope='col'>valor_compra</th>-->

                                                                                                            <th scope='col' class="text-right">Ação</th>



                                                                                                        </tr>

                                                                                                    </tfoot>

                                                                                                    <tbody>

                                                                                                                <?php foreach ($view_listar_outros AS $listar_outros):  ?>                                              

                                                                                                                <tr> 


 
                                                                                                                    <td><?php echo $listar_outros['id']; ?></td>

                                                                                                                    <td><?php echo $listar_outros['descricao']; ?></td>

                                                                                                                     <td><?php echo $listar_outros['quantidade']; ?></td>

                                                                                                                    <td><?php echo $listar_outros['valor_venda']; ?></td>
                                                                                                                    <td><?php $total_outros=$total_outros+($listar_outros['valor_venda']*$listar_outros['quantidade']); echo $listar_outros['valor_venda']; ?></td>

                                                                                                                    <td><?php echo $listar_outros['valor_desconto']; ?></td>

                                                                                                                    <td class='text-right'>                                                   

                                                                                                                        <form class='form-check-inline'><a onclick="return confirm('Tem Certeza que deseja EXCLUIR ?');"   href='/Itens/excluir/id/<?php echo $listar_outros['id']."/id_tabela/".$listar_venda["id"]; ?>' class='btn btn-sm btn-danger btn-just-icon '><i class='material-icons'>close</i></a></form>

                                                                                                                    </td>                    

                                                                                                                 </tr>

                                                                                                            <?php endforeach; ?> 

                                                                                                        </tbody>

                                                                                                    </table>

                                                                                                </div>

                                                                                            </div>

                                                                                        </div>                                             

                                                                                   </div>                                                                                       

                                                                                </div>

                                                                            </div>    

                                                                            

                                                                        </div>

                                                                    </div>

                                                                </div>

                                                            </div

                                                        </div>

                                        

                                                        <div class="col-md-8 card-header card-header-tabs card-header-rose row">

                                                            <div class="nav-tabs-navigation">

                                                                <div class="nav-tabs-wrapper">

                                                                    <span class="nav-tabs-title"></span>

                                                                    <ul class="nav nav-tabs" data-tabs="tabs">

                                                                        <li class="nav-item ">

                                                                            <a class="nav-link active" href="#" data-toggle="tab">

                                                                                <i class="material-icons">shopping_basket</i> <?php echo 'R$' . number_format($total_venda, 2, ',', '.'); ?>

                                                                                <div class="ripple-container"></div>

                                                                            </a>

                                                                        </li>

                                                                        <li class="nav-item">

                                                                            <a class="nav-link" href="#" data-toggle="tab">

                                                                                <i class="material-icons">settings_input_composite</i> <?php echo 'R$' . number_format($total_servico, 2, ',', '.'); ?>

                                                                                <div class="ripple-container"></div>

                                                                            </a>

                                                                        </li> 

                                                                        <li class="nav-item">

                                                                            <a class="nav-link" href="#" data-toggle="tab">

                                                                                <i class="material-icons">library_books</i> <?php echo 'R$' . number_format($total_outros, 2, ',', '.'); $total_geral=$total_venda+$total_servico+$total_outros; ?>

                                                                                <div class="ripple-container"></div>

                                                                            </a>

                                                                        </li> 

                                                                        <li class="nav-item">

                                                                            <a class="nav-link" href="#" data-toggle="tab">

                                                                                <i class="material-icons">total </i> <?php echo 'R$' . number_format($total_geral, 2, ',', '.');  ?>

                                                                                <div class="ripple-container"></div>

                                                                            </a>

                                                                        </li> 
                                                                    </ul>

                                                                </div>                                                                            

                                                            </div>

                                                        </div>

                                        <input id='' type='hidden'name='valor_total' class='form-control' required='true' value='<?php echo $total_geral;?>'> 
                                        

                                        

                                                    <!--<div class="col-md-2 card-header card-header-tabs  row">-->    
                                                        <tr>
                                                            <td><input type='submit' name='opcao' class=' btn btn-rose nav-link' required='' value="Salvar"></td>
                                                            <td> <a  href='/Cupom/nf_termica/id/<?php echo $listar_venda["id"]."/pago/$total_geral/" ?>' class='btn btn-rose nav-link '>Cupom</a></td>
                                                            <td><input type='submit' name='opcao' class=' btn btn-rose nav-link' required='' value="Finalizar"></td>
                                                        </tr>
                                                        
                                                    <!--</div>--> 
                                        
                                        

                                   

                                </div>

                           </form>

                       </div>

                   </div>

                </div>

            </div>

        </div>
           <script>
             $(document).ready(function() {
              $('#tabela').DataTable({
                'paging': false,
                'lengthMenu': [
                  [10, 25, 50, -1],
                  [10, 25, 50, 'ALL']
                ],
                responsive: true,
                language: {
                  search: '_INPUT_',
                  searchPlaceholder: 'Pesquisa',
                }
              });
            
            });
            $(document).ready(function() {
              $('#tabela1').DataTable({
                'paging': false,
                'lengthMenu': [
                  [10, 25, 50, -1],
                  [10, 25, 50, 'ALL']
                ],
                responsive: true,
                language: {
                  search: '_INPUT_',
                  searchPlaceholder: 'Pesquisa',
                }
              });
            
            });
            
               $(document).ready(function() {
              $('#tabela2').DataTable({
                'paging': false,
                'lengthMenu': [
                  [10, 25, 50, -1],
                  [10, 25, 50, 'ALL']
                ],
                responsive: true,
                language: {
                  search: '_INPUT_',
                  searchPlaceholder: 'Pesquisa',
                }
              });
            
            });
          </script>
          <script src='/web-files/sistema/js/jquery.dataTables.min.js'></script>

<br><br> <?php endforeach; } ?>
