<?php 
         //   require_once 'inicio.phtml';                 
            foreach ($view_listar_promocao AS $listar_promocao):
     ?>
    
        <div class='content'>
                <div class='container-fluid'>
                    <div class='row'>
                        <div class='col-md-12'>
                            <div class='card '>
                                <div class='card-header card-header-rose card-header-icon'>
                                    <div class='card-icon'>
                                        <i class='material-icons'>work_outline</i>
                                    </div>
                                    <h4 class='card-title'>Adicionar Itens a Promoção</h4>                                    
                                </div>
                               <form form enctype='multipart/form-data' method='post' action='/Contas/receita_incluir/'> <!-- PRECISA MEXER -->
                                    <div class='card-body '>
                                         <div class='row'>
                                                        <input id='' type='hidden'name='id'  required='true'value='<?php echo $listar_venda['id'] ?>'>
                                                        <input id='' type='hidden'name='id_tabela'  required='true'value='<?php echo $listar_venda['id'] ?>'>
                                                        <input id='' type='hidden'name='tabela'  required='true'value='Venda'>
                                                                                                             
                                                        
                                                        <div class='col-md-2'> 
                                                            <div class='form-group '>
                                                               <label  class='bmd-label-floating'>Filial</label>
                                                               <select id='id_filial' name='id_filial' class='form-control select' required='true' autocorrect='off' autocomplete='off'>
                                                                    <?php foreach ($view_listar_filial AS $listar_filial):                        
                                                                        if( $listar_filial['id'] == $listar_promocao['id_filial']){ ?>
                                                                              <option selected='true' value=' <?php echo $listar_filial['id'] ; ?>' ><?php echo $listar_filial['nome_fantasia'] ; ?></option>  <!--  PRECISA MEXER -->
                                                                          <?php }else{ ?>
                                                                              <option value=' <?php echo $listar_filial['id'] ; ?> '><?php echo $listar_filial['nome_fantasia'] ; ?></option>  <!-- PRECISA MEXER -->
                                                                    <?php  } endforeach; ?>
                                                               </select> 
                                                            </div>
                                                         </div>
                                                        
                                                        <div class='col-md-4'> 
                                                            <div class='form-group '>
                                                                <label  class='bmd-label-floating'>Descrição</label>
                                                                <input id='' type='text'name='descricao' class='form-control' required='true' value='<?php echo $listar_promocao['descricao'] ?>'>
                                                            </div>
                                                        </div>
                                                        
                                                        <div class='col-md-2'> 
                                                            <div class='form-group '>
                                                                <label  class='bmd-label-floating'>Data Inicial</label>
                                                                <input id='' type='date'name='data_inicio' class='form-control' required='true'value='<?php echo $listar_promocao['data_inicio'] ?>'>
                                                            </div>
                                                       </div>
                                                        
                                                        <div class='col-md-2'> 
                                                            <div class='form-group '>
                                                                <label  class='bmd-label-floating'>Data Final</label>
                                                                <input id='' type='date'name='data_fim' class='form-control' required='true'value='<?php echo $listar_promocao['data_fim'] ?>'>
                                                            </div>
                                                       </div>
                                                        
                                                        <div class='col-md-2'> 
                                                            <div class='form-group '>
                                                               <label  class='bmd-label-floating'>Status</label>
                                                               <select id='id_status' name='id_status' class='form-control select' required='true' autocorrect='off' autocomplete='off'>
                                                                    <?php foreach ($view_listar_status AS $listar_status):                        
                                                                        if( $listar_status['id'] == $listar_promocao['id_status']){ ?>
                                                                              <option selected='true' value=' <?php echo $listar_status['id'] ; ?>' ><?php echo $listar_status['descricao'] ; ?></option>  <!--  PRECISA MEXER -->
                                                                          <?php }else{ ?>
                                                                              <option value=' <?php echo $listar_status['id'] ; ?> '><?php echo $listar_status['descricao'] ; ?></option>  <!-- PRECISA MEXER -->
                                                                    <?php  } endforeach; ?>
                                                               </select> 
                                                            </div>
                                                         </div>

                                                            <div class='col-md-12'>
                                                                <div class='card'>
                                                                    <div class='card-header card-header-rose card-header-icon'>
                                                                        <div class='card-icon'>
                                                                            <i class='material-icons'>account_balance_wallet</i> 
                                                                        </div>
                                                                        <h4 class='card-title'>Itens</h4>
                                                                        <a href='/Promocao/form_item_promocao/id_tabela/<?php echo $listar_promocao["id"]."/tabela/Promocao/" ;?>' type='submit' class='btn btn-md btn-rose pull-right  '><i class='material-icons '>add_circle_outline</i></a>
                                                                    </div>
                                                                    <div class='card-body'>
                                                                        <div class='toolbar'> </div>
                                                                        <div class='material-datatables'>
                                                                            <table id='tabela1' class='table table-striped table-no-bordered table-hover' cellspacing='0' width='100%' style='width:100%'>
                                                                              <thead>
                                                                                <tr> 
                                                                                    <th style="font-size:0.9rem;  font-weight: bold;"scope='col'>Produto</th>
                                                                                    <th style="font-size:0.9rem;  font-weight: bold;"scope='col'>Descricao</th>
                                                                                    <th style="font-size:0.9rem;  font-weight: bold;"scope='col'>Valor de Venda</th>
                                                                                    <th style="font-size:0.9rem;  font-weight: bold;"scope='col'>Valor de Promoção</th>
                                                                                    
                                                                                </tr>
                                                                             <tfoot>
                                                                                <tr> 
                                                                                    <th style="font-size:0.9rem;  font-weight: bold;"scope='col'>Produto</th>
                                                                                    <th style="font-size:0.9rem;  font-weight: bold;"scope='col'>Descricao</th>
                                                                                    <th style="font-size:0.9rem;  font-weight: bold;"scope='col'>Valor de Venda</th>
                                                                                    <th style="font-size:0.9rem;  font-weight: bold;"scope='col'>Valor de Promoção</th>                                                                                   

                                                                                </tr>
                                                                            </tfoot>
                                                                            <tbody>
                                                                                        <?php foreach ($view_listar_itens AS $listar_itens):  ?>                                              
                                                                                        <tr> 

                                                                                            <td><?php echo $listar_itens['id_produto']; ?></td>
                                                                                            <td><?php echo $listar_itens['descricao']; ?></td>
                                                                                            <td><?php echo $listar_itens['valor_venda']; $total_venda=$total_venda+($listar_itens['valor_venda']*$listar_itens['quantidade']);?></td>
                                                                                            <td><?php echo $listar_itens['valor_promocao']; ?></td>
                                                                                     
                                                                                                           
                                                                                         </tr>
                                                                                    <?php endforeach; ?> 
                                                                                </tbody>
                                                                            </table>
                                                                        </div>                                                                        
                                                                       </div>                                                                    
                                                                </div>                                                               
                                                            </div>
                                                       
                                                        <div class='card-footer text-right'>
                                       </div>
                                    </div>
                                </div>
                           </form>
                       </div>
                   </div>
                </div>
            </div>
        </div>
<br><br> <?php endforeach;  ?>

     <!-- ===== AUTOCOMPLETAR ===== -->

        <link href="/web-files/js/auto_complete/jquery-ui.css" rel="stylesheet" type="text/css"/> 
        <script src="/web-files/js/auto_complete/jquery-1.11.1.min.js" type="text/javascript"></script>        
        <script src="/web-files/js/auto_complete/jquery-ui.min.js" type="text/javascript"></script>
        <script src="/web-files/js/auto_complete/jquery.select-to-autocomplete.js" type="text/javascript"></script>     

        <script>
          (function($){
            $(function(){
              $('select').selectToAutocomplete();
            });
          })(jQuery);
          </script>

    <!-- ===== FIM AUTOCOMPLETAR ===== -->