<?php
  //  require_once 'inicio.phtml';
    
    
  
?>
<div class='content'>
    <div class='container-fluid'>
    <div class='col-md-12'>
        <div class='row'>                        
            <?php    foreach ($view_listar_mesa as $listar_mesa): ?>
            <div class='col-md-3'>
                <div class='card ' style="background: <?php echo $listar_mesa["cor"]; ?>">                                
                    <div class='card-header card-header-rose card-header-icon' >
                        <div class='card-icon'>
                            <i class='material-icons'>event_seat</i>
                        </div>
                        <h3 class='card-title'>Mesa - <?php echo $listar_mesa["descricao_mesa"] ?></h3>
                    </div>
                    
                        <div class='card-body '>
                            <div class='row'>
                                <div class='col-md-2'> 
                                    <div class='form-group '>
                                       <label  class='bmd-label-floating'>MESA</label>
                                       <a><i class='material-icons'></i></a>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class='card-footer text-right'>
                                    <form action="/Mesa/pedido_mesa/"><button type='submit' name='' class='btn btn-rose btn-sm' required=''>Pedido</button></form>
                                    <form><button type='submit' name='' class='btn btn-rose btn-sm' required=''>Fechar</button></form>
                                    
                                </div>
                            </div>
                        </div>
                    
            </div>
        </div>
        
        <?php endforeach; ?>
    </div>
    </div>
</div>
