<?php 
  //  require_once 'inicio.phtml';
?>
    <div class='content'>
        <div class='container-fluid'>
            <div class='row'>
                <div class='col-md-6'>
                    <div class='card'>
                        <div class='card-header card-header-rose card-header-icon'>
                            <div class='card-icon'>
                                <i class='material-icons'>account_balance_wallet</i>
                            </div>
                            <h4 class='card-title'>Configurações Login</h4>
                            <a href='/Upload/form/id_tabela/0/tabela/Sistema/' type='submit' class='btn btn-sm btn-rose pull-right  '><i class='material-icons '>add_circle_outline</i></a>   
                        </div>
                        <div class='card-body'>
                            <div class='toolbar'> </div>
                            <div class='material-datatables'>
                                <table id='tabela1' class='table table-striped table-no-bordered table-hover' cellspacing='0' width='100%' style='width:100%'>
                                    <thead>         
                                        <tr> 
                                            <th style="font-size:0.9rem;  font-weight: bold;"scope='col'>Imagem</th>
                                            <th style="font-size:0.9rem;  font-weight: bold;"scope='col'>Tipo</th>
                                            <th style="font-size:0.9rem;  font-weight: bold;"scope='col'>Status</th>
                                            <th style="font-size:0.9rem;  font-weight: bold;"scope='col'class="text-right">Ação</th>
                                        </tr>       
                                    </thead>
                                    <tfoot>
                                        <tr> 
                                            <th style="font-size:0.9rem;  font-weight: bold;"scope='col'>Imagem</th>
                                            <th style="font-size:0.9rem;  font-weight: bold;"scope='col'>Tipo</th>
                                            <th style="font-size:0.9rem;  font-weight: bold;"scope='col'>Status</th>
                                            <th style="font-size:0.9rem;  font-weight: bold;"scope='col'class="text-right">Ação</th>
                                        </tr>
                                            </tfoot>
                                            <tbody>
                                            <?php foreach ($view_listar_imagens AS $listar_imagens):  ?>
                                                <tr> 
                                                    <td><img style="width: 90px;height: 60px" src="<?php echo $listar_imagens['src']; ?>" alt=""/></td>
                                                    <td><?php echo $listar_imagens['tipo']; ?></td>
                                                    <td><?php echo $listar_imagens['id_status']; ?></td>
                                                    <td class='text-right'>                                            
                                                        <form class='form-check-inline'><a href='<?php echo $listar_imagens['src']; ?>' type='submit' class='btn btn-sm btn-rose btn-just-icon ' ><i class='material-icons'>remove_red_eye</i></a></form>
                                                        <form class='form-check-inline'><a onclick="return confirm('Você tem certeza que deseja Excluir este registro ?');"   href='/Configuracao/excluir/id/<?php echo $listar_imagens['id']; ?>' class='btn btn-sm btn-danger btn-just-icon '><i class='material-icons'>close</i></a></form>
                                                    </td>                    
                                                </tr>
                                        <?php endforeach; ?> 
                                    </tbody>
                                </table>
                                
                            </div>
                        </div>
                    </div>
                </div>
                
                
                
                <div class='col-md-6'>
                    <div class='card'>
                        <div class='card-header card-header-rose card-header-icon'>
                            <div class='card-icon'>
                                <i class='material-icons'>account_balance_wallet</i>
                            </div>
                            <h4 class='card-title'>Configurações Menu</h4>
                            <a href='/Upload/form/id_tabela/0/tabela/Menu/' type='submit' class='btn btn-sm btn-rose pull-right  '><i class='material-icons '>add_circle_outline</i></a>   
                        </div>
                        <div class='card-body'>
                            <div class='toolbar'> </div>
                            <div class='material-datatables'>
                                <table id='tabela1' class='table table-striped table-no-bordered table-hover' cellspacing='0' width='100%' style='width:100%'>
                                    <thead>         
                                        <tr> 
                                            <th style="font-size:0.9rem;  font-weight: bold;"scope='col'>Imagem</th>
                                            <th style="font-size:0.9rem;  font-weight: bold;"scope='col'>Tipo</th>
                                            <th style="font-size:0.9rem;  font-weight: bold;"scope='col'>Status</th>
                                            <th style="font-size:0.9rem;  font-weight: bold;"scope='col'class="text-right">Ação</th>
                                        </tr>       
                                    </thead>
                                    <tfoot>
                                        <tr> 
                                            <th style="font-size:0.9rem;  font-weight: bold;"scope='col'>Imagem</th>
                                            <th style="font-size:0.9rem;  font-weight: bold;"scope='col'>Tipo</th>
                                            <th style="font-size:0.9rem;  font-weight: bold;"scope='col'>Status</th>
                                            <th style="font-size:0.9rem;  font-weight: bold;"scope='col'class="text-right">Ação</th>
                                        </tr>
                                            </tfoot>
                                            <tbody>
                                            <?php foreach ($view_listar_menu AS $listar_menu):  ?>
                                                <tr> <td><img style="width: 90px;height: 60px" src="<?php echo $listar_menu['src']; ?>" alt=""/></td>
                                                    <td><?php echo $listar_menu['tipo']; ?></td>                                                    
                                                    <td><?php echo $listar_menu['id_status']; ?></td>
                                                    <td class='text-right'>                                            
                                                        <form class='form-check-inline'><a href='<?php echo $listar_menu['src']; ?>' type='submit' class='btn btn-sm btn-rose btn-just-icon ' ><i class='material-icons'>remove_red_eye</i></a></form>
                                                        <form class='form-check-inline'><a onclick="return confirm('Você tem certeza que deseja Excluir este registro ?');"   href='/Configuracao/excluir/id/<?php echo $listar_menu['id']; ?>' class='btn btn-sm btn-danger btn-just-icon '><i class='material-icons'>close</i></a></form>
                                                    </td>                    
                                                </tr>
                                        <?php endforeach; ?> 
                                    </tbody>
                                </table>
                                
                            </div>
                        </div>
                    </div>
                </div>
                
                
            </div>
        </div>
    </div>