<!DOCTYPE html>
<html lang="pt_br">
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport'/>
        
        <link href="/web-files/sistema/css/material-dashboard.css" rel="stylesheet"/>
        <link href="/web-files/sistema/css/material-dashboard.css?v=2.1.0" rel="stylesheet"/>
        <link href="/web-files/sistema/css/demo.css" rel="stylesheet"/>
        <link href="/web-files/sistema/css/pg-restaurant.css" rel="stylesheet"/>
        <link href="/web-files/sistema/js/auto_complete/jquery-ui.css" rel="stylesheet" type="text/css"/>
        
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">        

        <title> Acesso Restrito </title>
    </head>
    
    
    <body class="off-canvas-sidebar">
        <div class="col-md-3"></div>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top text-white">
            <div class="container">
                <div class="navbar-wrapper">
                    <a class="navbar-brand" href="#pablo">
                        <img src="/web-files/sistema/imagens/univale.png" width="100"/>
                    </a>
                </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="navbar-toggler-icon icon-bar"></span>
                    <span class="navbar-toggler-icon icon-bar"></span>
                    <span class="navbar-toggler-icon icon-bar"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end">
                    <ul class="navbar-nav">
                        <li class="nav-item ">
                            <a href="javascript:history.back()" class="nav-link"> <i class="material-icons">keyboard_arrow_left</i> Voltar </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- End Navbar -->
        <div class="wrapper wrapper-full-page">
            <div class="page-header error-page header-filter" style="background-image: url('/web-files/image/serkfc.jpg'); background-position: center center; background-repeat: repeat; background-size: auto;">
                <!--   you can change the color of the filter page using: data-color="blue | green | orange | red | purple" -->
                <div class="content-center">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="title"> <i class="material-icons" style="font-size:8rem;">lock</i> </h1> 
                            <h2>NÃO AUTORIZADO</h2>
                            <h6>Usuário sem permissão para executar ação requisitada.</h6>
                        </div>
                    </div>
                </div>
                
            </div>
            
        </div>
        
        <!--   Core JS Files   -->
         <script src="/web-files/sistema/js/core/jquery.min.js"></script>       
        <script src="/web-files/sistema/js/core/pg-restaurant.js"></script>     
        <script src="/web-files/sistema/js/core/popper.min.js"></script>        
        <script src="/web-files/sistema/js/core/bootstrap-material-design.min.js"></script>   
        
        <script src="/web-files/sistema/js/plugins/perfect-scrollbar.jquery.min.js"></script>
        <script src="/web-files/sistema/js/plugins/moment.min.js"></script>     
        <script src="/web-files/sistema/js/plugins/sweetalert2.js"></script>        
        <script src="/web-files/sistema/js/plugins/jquery.validate.min.js"></script>        
        <script src="/web-files/sistema/js/js/plugins/jquery.bootstrap-wizard.js"></script> 
        <script src="/web-files/sistema/js/plugins/bootstrap-selectpicker.js"></script>
        <script src="/web-files/sistema/js/plugins/bootstrap-datetimepicker.min.js"></script>
        <script src="/web-files/sistema/js/plugins/jquery.dataTables.min.js"></script>
        <script src="/web-files/sistema/js/plugins/bootstrap-tagsinput.js"></script>      
        <script src="/web-files/sistema/js/plugins/jasny-bootstrap.min.js"></script>
        <script src="/web-files/sistema/js/plugins/fullcalendar.min.js"></script>
        <script src="/web-files/sistema/js/plugins/jquery-jvectormap.js"></script>
        <script src="/web-files/sistema/js/plugins/nouislider.min.js"></script>       
        <script src="/web-files/sistema/js/plugins/chartist.min.js"></script>
        <script src="/web-files/sistema/js/plugins/bootstrap-notify.js"></script>
        
        <script src="/web-files/sistema/js/material-dashboard.js?v=2.1.0" type="text/javascript"></script>
        <script src="/web-files/sistema/js/demo/demo.js"></script>
        <script src="/web-files/sistema/js/auto_complete/jquery-1.11.1.min.js" type="text/javascript"></script>        
        <script src="/web-files/sistema/js/auto_complete/jquery-ui.min.js" type="text/javascript"></script>
        <script src="/web-files/sistema/js/auto_complete/jquery.select-to-autocomplete.js" type="text/javascript"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
        <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
        <script>
    $(document).ready(function() {
      $().ready(function() {
        $sidebar = $('.sidebar');

        $sidebar_img_container = $sidebar.find('.sidebar-background');

        $full_page = $('.full-page');

        $sidebar_responsive = $('body > .navbar-collapse');

        window_width = $(window).width();

        fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();

        if (window_width > 767 && fixed_plugin_open == 'Dashboard') {
          if ($('.fixed-plugin .dropdown').hasClass('show-dropdown')) {
            $('.fixed-plugin .dropdown').addClass('open');
          }

        }

        $('.fixed-plugin a').click(function(event) {
          // Alex if we click on switch, stop propagation of the event, so the dropdown will not be hide, otherwise we set the  section active
          if ($(this).hasClass('switch-trigger')) {
            if (event.stopPropagation) {
              event.stopPropagation();
            } else if (window.event) {
              window.event.cancelBubble = true;
            }
          }
        });

        $('.fixed-plugin .active-color span').click(function() {
          $full_page_background = $('.full-page-background');

          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data-color', new_color);
          }

          if ($full_page.length != 0) {
            $full_page.attr('filter-color', new_color);
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.attr('data-color', new_color);
          }
        });

        $('.fixed-plugin .background-color .badge').click(function() {
          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('background-color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data-background-color', new_color);
          }
        });

        $('.fixed-plugin .img-holder').click(function() {
          $full_page_background = $('.full-page-background');

          $(this).parent('li').siblings().removeClass('active');
          $(this).parent('li').addClass('active');


          var new_image = $(this).find("img").attr('src');

          if ($sidebar_img_container.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
            $sidebar_img_container.fadeOut('fast', function() {
              $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
              $sidebar_img_container.fadeIn('fast');
            });
          }

          if ($full_page_background.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
            var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

            $full_page_background.fadeOut('fast', function() {
              $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
              $full_page_background.fadeIn('fast');
            });
          }

          if ($('.switch-sidebar-image input:checked').length == 0) {
            var new_image = $('.fixed-plugin li.active .img-holder').find("img").attr('src');
            var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

            $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
            $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.css('background-image', 'url("' + new_image + '")');
          }
        });

        $('.switch-sidebar-image input').change(function() {
          $full_page_background = $('.full-page-background');

          $input = $(this);

          if ($input.is(':checked')) {
            if ($sidebar_img_container.length != 0) {
              $sidebar_img_container.fadeIn('fast');
              $sidebar.attr('data-image', '#');
            }

            if ($full_page_background.length != 0) {
              $full_page_background.fadeIn('fast');
              $full_page.attr('data-image', '#');
            }

            background_image = true;
          } else {
            if ($sidebar_img_container.length != 0) {
              $sidebar.removeAttr('data-image');
              $sidebar_img_container.fadeOut('fast');
            }

            if ($full_page_background.length != 0) {
              $full_page.removeAttr('data-image', '#');
              $full_page_background.fadeOut('fast');
            }

            background_image = false;
          }
        });

        $('.switch-sidebar-mini input').change(function() {
          $body = $('body');

          $input = $(this);

          if (md.misc.sidebar_mini_active == true) {
            $('body').removeClass('sidebar-mini');
            md.misc.sidebar_mini_active = false;

            $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar();

          } else {

            $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar('destroy');

            setTimeout(function() {
              $('body').addClass('sidebar-mini');

              md.misc.sidebar_mini_active = true;
            }, 300);
          }

          // we simulate the window Resize so the charts will get updated in realtime.
          var simulateWindowResize = setInterval(function() {
            window.dispatchEvent(new Event('resize'));
          }, 180);

          // we stop the simulation of Window Resize after the animations are completed
          setTimeout(function() {
            clearInterval(simulateWindowResize);
          }, 1000);

        });
      });
    });
  </script>
        <script>
    $(document).ready(function() {
      md.checkFullPageBackgroundImage();
    });
  </script>
    </body>
</html>