<?php class Programa extends Controller {   
    private  $auth,$db;
    public function acesso_restrito(){          
        $this->auth = new AutenticaHelper();
        $this->auth->setLoginControllerAction('Index','')
                   ->checkLogin('redirect');              
        $this->db = new AdminModel(); 
    }       
    public function admin_listar(){
        $this->acesso_restrito();
        $acesso = new AcessoHelper();
        $logs = new LogsModel();
        $comando="/".__CLASS__."/incluir/";         
        if($acesso->acesso_valida("/".__CLASS__."/admin_listar/")==true){ 
            $filiais=$acesso->acesso_filial(__CLASS__);
            $status= new StatusModel();
            $filial = new FilialModel();           
            $acesso = new SessionHelper();           
            $programa = new ProgramaModel();            
            if(empty($_POST["pesquisa"])){$pesquisa=null; }else{ $pesquisa=$_POST["pesquisa"]; }
            $menu = new MenuHelper("Bit a Bits", $Class, $AcaoForm, $MetodoDeEnvio);        
            echo $menu->Menu();            
            $form = new FormularioHelper();     
            $inputs.= $form->Listar("col-md-12", null, "/".__CLASS__."/form/", $icone,$programa->listar_programa("INNER JOIN Status ON Status.id=Programa.id_status","25","Programa.id_status<>'99'",NULL,' Programa.comando ASC',"Programa.id,Programa.descricao AS 'Descrição',Programa.tipo AS Tipo, Programa.versao AS 'Versão',Programa.icone AS 'Icone',Status.cor AS 'cor_Status',Status.descricao AS 'Status',Programa.ordem AS 'Posição',Programa.data_lancamento AS 'Data Lançamento'",null,$pesquisa), "tabela1", array(array("acao"=>"/".__CLASS__."/form/","classe"=>"btn-sm btn-warning","icone"=>"edit"),array("acao"=>"/".__CLASS__."/visualizar/","classe"=>"btn-sm btn-rose","icone"=>"remove_red_eye"),array("acao"=>"/Logs/form/","classe"=>"btn-sm btn-danger","icone"=>"close")));
            $form->card(__CLASS__,$inputs,"col-md-12",$comando,"POST","api");
        }else{
            $this->view('error_permisao');
        }    
    }

   public function form(){ 
        $this->acesso_restrito();
        $acesso = new AcessoHelper();         
        $comando="/".__CLASS__."/incluir/";  
        if($acesso->acesso_valida("/".__CLASS__."/admin_listar/")==true){    
            $logs = new LogsModel();           
            $status= new StatusModel();
            $filial = new FilialModel();
            $programa = new ProgramaModel(); 
            $acesso = new SessionHelper();
            $menu = new MenuHelper("B", $Class, $AcaoForm, $MetodoDeEnvio);        
            echo $menu->Menu();           
           $id=$this->getParams("id");  
            $nome_form="Cadastra Programa";
            $listar_programa= $programa->listar_programa($join, $limit, "id_status<>'99'", $offset, $orderby, $from);                            
            if(!empty($id)){
                $programa_dados=$programa->listar_programa($join, "1", "id='$id'", $offset, $orderby);
                $programa_dados= $programa_dados[0]; 
                $comando="/".__CLASS__."/alterar/";
                $nome_form="Alterar Programa";
            }            
        $icone= array(
        array("id"=>"3d_rotation","icone" => "3d_rotation"),
        array("id"=>"access_alarm","icone" => "access_alarm"),
        array("id"=>"access_alarms","icone" => "access_alarms"),
        array("id"=>"access_time","icone" => "access_time"),
        array("id"=>"accessibility","icone" => "accessibility"),
        array("id"=>"account_balance","icone" => "account_balance"),
        array("id"=>"account_balance_wallet","icone" => "account_balance_wallet"),
        array("id"=>"account_box","icone" => "account_box"),
        array("id"=>"account_circle","icone" => "account_circle"),
        array("id"=>"adb","icone" => "adb"),
        array("id"=>"add","icone" => "add"),
        array("id"=>"add_alarm","icone" => "add_alarm"),
        array("id"=>"add_alert","icone" => "add_alert"),
        array("id"=>"add_box","icone" => "add_box"),
        array("id"=>"add_circle","icone" => "add_circle"),
        array("id"=>"add_circle_outline","icone" => "add_circle_outline"),
        array("id"=>"add_shopping_cart","icone" => "add_shopping_cart"),
        array("id"=>"add_to_photos","icone" => "add_to_photos"),
        array("id"=>"adjust","icone" => "adjust"),
        array("id"=>"airline_seat_flat","icone" => "airline_seat_flat"),
        array("id"=>"airline_seat_flat_angled","icone" => "airline_seat_flat_angled"),
        array("id"=>"airline_seat_individual_suite","icone" => "airline_seat_individual_suite"),
        array("id"=>"airline_seat_legroom_extra","icone" => "airline_seat_legroom_extra"),
        array("id"=>"airline_seat_legroom_normal","icone" => "airline_seat_legroom_normal"),
        array("id"=>"airline_seat_legroom_reduced","icone" => "airline_seat_legroom_reduced"),
        array("id"=>"airline_seat_recline_extra","icone" => "airline_seat_recline_extra"),
        array("id"=>"airline_seat_recline_normal","icone" => "airline_seat_recline_normal"),
        array("id"=>"airplanemode_active","icone" => "airplanemode_active"),
        array("id"=>"airplanemode_inactive","icone" => "airplanemode_inactive"),
        array("id"=>"airplay","icone" => "airplay"),
        array("id"=>"alarm","icone" => "alarm"),
        array("id"=>"alarm_add","icone" => "alarm_add"),
        array("id"=>"alarm_off","icone" => "alarm_off"),
        array("id"=>"alarm_on","icone" => "alarm_on"),
        array("id"=>"album","icone" => "album"),
        array("id"=>"android","icone" => "android"),
        array("id"=>"announcement","icone" => "announcement"),
        array("id"=>"apps","icone" => "apps"),
        array("id"=>"archive","icone" => "archive"),
        array("id"=>"arrow_back","icone" => "arrow_back"),
        array("id"=>"arrow_drop_down","icone" => "arrow_drop_down"),
        array("id"=>"arrow_drop_down_circle","icone" => "arrow_drop_down_circle"),
        array("id"=>"arrow_drop_up","icone" => "arrow_drop_up"),
        array("id"=>"arrow_forward","icone" => "arrow_forward"),
        array("id"=>"aspect_ratio","icone" => "aspect_ratio"),
        array("id"=>"assessment","icone" => "assessment"),
        array("id"=>"assignment","icone" => "assignment"),
        array("id"=>"assignment_ind","icone" => "assignment_ind"),
        array("id"=>"assignment_late","icone" => "assignment_late"),
        array("id"=>"assignment_return","icone" => "assignment_return"),
        array("id"=>"assignment_returned","icone" => "assignment_returned"),
        array("id"=>"assignment_turned_in","icone" => "assignment_turned_in"),
        array("id"=>"assistant","icone" => "assistant"),
        array("id"=>"assistant_photo","icone" => "assistant_photo"),
        array("id"=>"attach_file","icone" => "attach_file"),
        array("id"=>"attach_money","icone" => "attach_money"),
        array("id"=>"attachment","icone" => "attachment"),
        array("id"=>"audiotrack","icone" => "audiotrack"),
        array("id"=>"autorenew","icone" => "autorenew"),
        array("id"=>"av_timer","icone" => "av_timer"),
        array("id"=>"backspace","icone" => "backspace"),
        array("id"=>"backup","icone" => "backup"),
        array("id"=>"battery_alert","icone" => "battery_alert"),
        array("id"=>"battery_charging_full","icone" => "battery_charging_full"),
        array("id"=>"battery_full","icone" => "battery_full"),
        array("id"=>"battery_std","icone" => "battery_std"),
        array("id"=>"battery_unknown","icone" => "battery_unknown"),
        array("id"=>"beenhere","icone" => "beenhere"),
        array("id"=>"block","icone" => "block"),
        array("id"=>"bluetooth","icone" => "bluetooth"),
        array("id"=>"bluetooth_audio","icone" => "bluetooth_audio"),
        array("id"=>"bluetooth_connected","icone" => "bluetooth_connected"),
        array("id"=>"bluetooth_disabled","icone" => "bluetooth_disabled"),
        array("id"=>"bluetooth_searching","icone" => "bluetooth_searching"),
        array("id"=>"blur_circular","icone" => "blur_circular"),
        array("id"=>"blur_linear","icone" => "blur_linear"),
        array("id"=>"blur_off","icone" => "blur_off"),
        array("id"=>"blur_on","icone" => "blur_on"),
        array("id"=>"book","icone" => "book"),
        array("id"=>"bookmark","icone" => "bookmark"),
       array("id"=>"bookmark_border","icone" => "bookmark_border"),
        array("id"=>"border_all","icone" => "border_all"),
        array("id"=>"border_bottom","icone" => "border_bottom"),
        array("id"=>"border_clear","icone" => "border_clear"),
        array("id"=>"border_color","icone" => "border_color"),
        array("id"=>"border_horizontal","icone" => "border_horizontal"),
        array("id"=>"border_inner","icone" => "border_inner"),
        array("id"=>"border_left","icone" => "border_left"),
        array("id"=>"border_outer","icone" => "border_outer"),
        array("id"=>"border_right","icone" => "border_right"),
        array("id"=>"border_style","icone" => "border_style"),
        array("id"=>"border_top","icone" => "border_top"),
        array("id"=>"border_vertical","icone" => "border_vertical"),
        array("id"=>"brightness_1","icone" => "brightness_1"),
        array("id"=>"brightness_2","icone" => "brightness_2"),
        array("id"=>"brightness_3","icone" => "brightness_3"),
        array("id"=>"brightness_4","icone" => "brightness_4"),
        array("id"=>"brightness_5","icone" => "brightness_5"),
        array("id"=>"brightness_6","icone" => "brightness_6"),
        array("id"=>"brightness_7","icone" => "brightness_7"),
        array("id"=>"brightness_auto","icone" => "brightness_auto"),
        array("id"=>"brightness_high","icone" => "brightness_high"),
        array("id"=>"brightness_low","icone" => "brightness_low"),
        array("id"=>"brightness_medium","icone" => "brightness_medium"),
        array("id"=>"broken_image","icone" => "broken_image"),
        array("id"=>"brush","icone" => "brush"),
        array("id"=>"bug_report","icone" => "bug_report"),
        array("id"=>"build","icone" => "build"),
        array("id"=>"business","icone" => "business"),
        array("id"=>"cached","icone" => "cached"),
        array("id"=>"cake","icone" => "cake"),
        array("id"=>"call","icone" => "call"),
        array("id"=>"call_end","icone" => "call_end"),
        array("id"=>"call_made","icone" => "call_made"),
        array("id"=>"call_merge","icone" => "call_merge"),
        array("id"=>"call_missed","icone" => "call_missed"),
        array("id"=>"call_received","icone" => "call_received"),
        array("id"=>"call_split","icone" => "call_split"),
        array("id"=>"camera","icone" => "camera"),
        array("id"=>"camera_alt","icone" => "camera_alt"),
        array("id"=>"camera_enhance","icone" => "camera_enhance"),
        array("id"=>"camera_front","icone" => "camera_front"),
        array("id"=>"camera_rear","icone" => "camera_rear"),
        array("id"=>"camera_roll","icone" => "camera_roll"),
        array("id"=>"cancel","icone" => "cancel"),
        array("id"=>"card_giftcard","icone" => "card_giftcard"),
        array("id"=>"card_membership","icone" => "card_membership"),
        array("id"=>"card_travel","icone" => "card_travel"),
        array("id"=>"cast","icone" => "cast"),
        array("id"=>"cast_connected","icone" => "cast_connected"),
        array("id"=>"center_focus_strong","icone" => "center_focus_strong"),
        array("id"=>"center_focus_weak","icone" => "center_focus_weak"),
        array("id"=>"change_history","icone" => "change_history"),
        array("id"=>"chat","icone" => "chat"),
        array("id"=>"chat_bubble","icone" => "chat_bubble"),
        array("id"=>"chat_bubble_outline","icone" => "chat_bubble_outline"),
        array("id"=>"check","icone" => "check"),
        array("id"=>"check_box","icone" => "check_box"),
        array("id"=>"check_box_outline_blank","icone" => "check_box_outline_blank"),
        array("id"=>"check_circle","icone" => "check_circle"),
        array("id"=>"chevron_left","icone" => "chevron_left"),
        array("id"=>"chevron_right","icone" => "chevron_right"),
        array("id"=>"chrome_reader_mode","icone" => "chrome_reader_mode"),
        array("id"=>"class","icone" => "class"),
        array("id"=>"clear","icone" => "clear"),
        array("id"=>"clear_all","icone" => "clear_all"),
        array("id"=>"close","icone" => "close"),
        array("id"=>"closed_caption","icone" => "closed_caption"),
        array("id"=>"cloud","icone" => "cloud"),
        array("id"=>"cloud_circle","icone" => "cloud_circle"),
        array("id"=>"cloud_done","icone" => "cloud_done"),
        array("id"=>"cloud_download","icone" => "cloud_download"),
        array("id"=>"cloud_off","icone" => "cloud_off"),
        array("id"=>"cloud_queue","icone" => "cloud_queue"),
        array("id"=>"cloud_upload","icone" => "cloud_upload"),
        array("id"=>"code","icone" => "code"),
        array("id"=>"collections","icone" => "collections"),
        array("id"=>"collections_bookmark","icone" => "collections_bookmark"),
        array("id"=>"color_lens","icone" => "color_lens"),
        array("id"=>"colorize","icone" => "colorize"),
        array("id"=>"comment","icone" => "comment"),
        array("id"=>"compare","icone" => "compare"),
        array("id"=>"computer","icone" => "computer"),
        array("id"=>"confirmation_number","icone" => "confirmation_number"),
        array("id"=>"contact_phone","icone" => "contact_phone"),
        array("id"=>"contacts","icone" => "contacts"),
        array("id"=>"content_copy","icone" => "content_copy"),
        array("id"=>"content_cut","icone" => "content_cut"),
        array("id"=>"content_paste","icone" => "content_paste"),
        array("id"=>"control_point","icone" => "control_point"),
        array("id"=>"control_point_duplicate","icone" => "control_point_duplicate"),
        array("id"=>"create","icone" => "create"),
        array("id"=>"credit_card","icone" => "credit_card"),
        array("id"=>"crop","icone" => "crop"),
        array("id"=>"crop_16_9","icone" => "crop_16_9"),
        array("id"=>"crop_3_2","icone" => "crop_3_2"),
        array("id"=>"crop_5_4","icone" => "crop_5_4"),
        array("id"=>"crop_7_5","icone" => "crop_7_5"),
        array("id"=>"crop_din","icone" => "crop_din"),
        array("id"=>"crop_free","icone" => "crop_free"),
        array("id"=>"crop_landscape","icone" => "crop_landscape"),
        array("id"=>"crop_original","icone" => "crop_original"),
        array("id"=>"crop_portrait","icone" => "crop_portrait"),
        array("id"=>"crop_square","icone" => "crop_square"),
        array("id"=>"dashboard","icone" => "dashboard"),
        array("id"=>"data_usage","icone" => "data_usage"),
        array("id"=>"dehaze","icone" => "dehaze"),
        array("id"=>"delete","icone" => "delete"),
        array("id"=>"description","icone" => "description"),
        array("id"=>"desktop_mac","icone" => "desktop_mac"),
        array("id"=>"desktop_windows","icone" => "desktop_windows"),
        array("id"=>"details","icone" => "details"),
        array("id"=>"developer_board","icone" => "developer_board"),
        array("id"=>"developer_mode","icone" => "developer_mode"),
        array("id"=>"device_hub","icone" => "device_hub"),
        array("id"=>"devices","icone" => "devices"),
        array("id"=>"dialer_sip","icone" => "dialer_sip"),
        array("id"=>"dialpad","icone" => "dialpad"),
        array("id"=>"directions","icone" => "directions"),
        array("id"=>"directions_bike","icone" => "directions_bike"),
        array("id"=>"directions_boat","icone" => "directions_boat"),
        array("id"=>"directions_bus","icone" => "directions_bus"),
        array("id"=>"directions_car","icone" => "directions_car"),
        array("id"=>"directions_railway","icone" => "directions_railway"),
        array("id"=>"directions_run","icone" => "directions_run"),
        array("id"=>"directions_subway","icone" => "directions_subway"),
        array("id"=>"directions_transit","icone" => "directions_transit"),
        array("id"=>"directions_walk","icone" => "directions_walk"),
        array("id"=>"disc_full","icone" => "disc_full"),
        array("id"=>"dns","icone" => "dns"),
        array("id"=>"do_not_disturb","icone" => "do_not_disturb"),
        array("id"=>"do_not_disturb_alt","icone" => "do_not_disturb_alt"),
        array("id"=>"dock","icone" => "dock"),
        array("id"=>"domain","icone" => "domain"),
        array("id"=>"done","icone" => "done"),
        array("id"=>"done_all","icone" => "done_all"),
        array("id"=>"drafts","icone" => "drafts"),
        array("id"=>"drive_eta","icone" => "drive_eta"),
        array("id"=>"dvr","icone" => "dvr"),
        array("id"=>"edit","icone" => "edit"),
        array("id"=>"eject","icone" => "eject"),
        array("id"=>"email","icone" => "email"),
        array("id"=>"equalizer","icone" => "equalizer"),
        array("id"=>"error","icone" => "error"),
        array("id"=>"error_outline","icone" => "error_outline"),
        array("id"=>"event","icone" => "event"),
        array("id"=>"event_available","icone" => "event_available"),
        array("id"=>"event_busy","icone" => "event_busy"),
        array("id"=>"event_note","icone" => "event_note"),
        array("id"=>"event_seat","icone" => "event_seat"),
        array("id"=>"exit_to_app","icone" => "exit_to_app"),
        array("id"=>"expand_less","icone" => "expand_less"),
        array("id"=>"expand_more","icone" => "expand_more"),
        array("id"=>"explicit","icone" => "explicit"),
        array("id"=>"explore","icone" => "explore"),
        array("id"=>"exposure","icone" => "exposure"),
        array("id"=>"exposure_neg_1","icone" => "exposure_neg_1"),
        array("id"=>"exposure_neg_2","icone" => "exposure_neg_2"),
        array("id"=>"exposure_plus_1","icone" => "exposure_plus_1"),
        array("id"=>"exposure_plus_2","icone" => "exposure_plus_2"),
        array("id"=>"exposure_zero","icone" => "exposure_zero"),
        array("id"=>"extension","icone" => "extension"),
        array("id"=>"face","icone" => "face"),
        array("id"=>"fast_forward","icone" => "fast_forward"),
        array("id"=>"fast_rewind","icone" => "fast_rewind"),
        array("id"=>"favorite","icone" => "favorite"),
        array("id"=>"favorite_border","icone" => "favorite_border"),
        array("id"=>"feedback","icone" => "feedback"),
        array("id"=>"file_download","icone" => "file_download"),
        array("id"=>"file_upload","icone" => "file_upload"),
       array("id"=>"filter","icone" => "filter"),
        array("id"=>"filter_1","icone" => "filter_1"),
        array("id"=>"filter_2","icone" => "filter_2"),
        array("id"=>"filter_3","icone" => "filter_3"),
        array("id"=>"filter_4","icone" => "filter_4"),
        array("id"=>"filter_5","icone" => "filter_5"),
        array("id"=>"filter_6","icone" => "filter_6"),
        array("id"=>"filter_7","icone" => "filter_7"),
        array("id"=>"filter_8","icone" => "filter_8"),
        array("id"=>"filter_9","icone" => "filter_9"),
        array("id"=>"filter_9_plus","icone" => "filter_9_plus"),
        array("id"=>"filter_b_and_w","icone" => "filter_b_and_w"),
        array("id"=>"filter_center_focus","icone" => "filter_center_focus"),
        array("id"=>"filter_drama","icone" => "filter_drama"),
        array("id"=>"filter_frames","icone" => "filter_frames"),
        array("id"=>"filter_hdr","icone" => "filter_hdr"),
        array("id"=>"filter_list","icone" => "filter_list"),
        array("id"=>"filter_none","icone" => "filter_none"),
        array("id"=>"filter_tilt_shift","icone" => "filter_tilt_shift"),
        array("id"=>"filter_vintage","icone" => "filter_vintage"),
        array("id"=>"find_in_page","icone" => "find_in_page"),
        array("id"=>"find_replace","icone" => "find_replace"),
        array("id"=>"flag","icone" => "flag"),
       array("id"=>"flare","icone" => "flare"),
        array("id"=>"flash_auto","icone" => "flash_auto"),
        array("id"=>"flash_off","icone" => "flash_off"),
        array("id"=>"flash_on","icone" => "flash_on"),
        array("id"=>"flight","icone" => "flight"),
        array("id"=>"flight_land","icone" => "flight_land"),
        array("id"=>"flight_takeoff","icone" => "flight_takeoff"),
        array("id"=>"flip","icone" => "flip"),
        array("id"=>"flip_to_back","icone" => "flip_to_back"),
        array("id"=>"flip_to_front","icone" => "flip_to_front"),
        array("id"=>"folder","icone" => "folder"),
        array("id"=>"folder_open","icone" => "folder_open"),
        array("id"=>"folder_shared","icone" => "folder_shared"),
        array("id"=>"folder_special","icone" => "folder_special"),
        array("id"=>"font_download","icone" => "font_download"),
        array("id"=>"format_align_center","icone" => "format_align_center"),
        array("id"=>"format_align_justify","icone" => "format_align_justify"),
        array("id"=>"format_align_left","icone" => "format_align_left"),
        array("id"=>"format_align_right","icone" => "format_align_right"),
        array("id"=>"format_bold","icone" => "format_bold"),
        array("id"=>"format_clear","icone" => "format_clear"),
        array("id"=>"format_color_fill","icone" => "format_color_fill"),
        array("id"=>"format_color_reset","icone" => "format_color_reset"),
        array("id"=>"format_color_text","icone" => "format_color_text"),
        array("id"=>"format_indent_decrease","icone" => "format_indent_decrease"),
        array("id"=>"format_indent_increase","icone" => "format_indent_increase"),
        array("id"=>"format_italic","icone" => "format_italic"),
        array("id"=>"format_line_spacing","icone" => "format_line_spacing"),
        array("id"=>"format_list_bulleted","icone" => "format_list_bulleted"),
        array("id"=>"format_list_numbered","icone" => "format_list_numbered"),
        array("id"=>"format_paint","icone" => "format_paint"),
        array("id"=>"format_quote","icone" => "format_quote"),
        array("id"=>"format_size","icone" => "format_size"),
        array("id"=>"format_strikethrough","icone" => "format_strikethrough"),
        array("id"=>"format_textdirection_l_to_r","icone" => "format_textdirection_l_to_r"),
        array("id"=>"format_textdirection_r_to_l","icone" => "format_textdirection_r_to_l"),
        array("id"=>"format_underlined","icone" => "format_underlined"),
        array("id"=>"forum","icone" => "forum"),
        array("id"=>"forward","icone" => "forward"),
        array("id"=>"forward_10","icone" => "forward_10"),
        array("id"=>"forward_30","icone" => "forward_30"),
        array("id"=>"forward_5","icone" => "forward_5"),
        array("id"=>"fullscreen","icone" => "fullscreen"),
        array("id"=>"fullscreen_exit","icone" => "fullscreen_exit"),
        array("id"=>"functions","icone" => "functions"),
        array("id"=>"gamepad","icone" => "gamepad"),
        array("id"=>"games","icone" => "games"),
        array("id"=>"gesture","icone" => "gesture"),
        array("id"=>"get_app","icone" => "get_app"),
        array("id"=>"gif","icone" => "gif"),
        array("id"=>"gps_fixed","icone" => "gps_fixed"),
        array("id"=>"gps_not_fixed","icone" => "gps_not_fixed"),
        array("id"=>"gps_off","icone" => "gps_off"),
        array("id"=>"grade","icone" => "grade"),
        array("id"=>"gradient","icone" => "gradient"),
        array("id"=>"grain","icone" => "grain"),
        array("id"=>"graphic_eq","icone" => "graphic_eq"),
        array("id"=>"grid_off","icone" => "grid_off"),
        array("id"=>"grid_on","icone" => "grid_on"),
        array("id"=>"group","icone" => "group"),
        array("id"=>"group_add","icone" => "group_add"),
        array("id"=>"group_work","icone" => "group_work"),
        array("id"=>"hd","icone" => "hd"),
        array("id"=>"hdr_off","icone" => "hdr_off"),
        array("id"=>"hdr_on","icone" => "hdr_on"),
        array("id"=>"hdr_strong","icone" => "hdr_strong"),
        array("id"=>"hdr_weak","icone" => "hdr_weak"),
        array("id"=>"headset","icone" => "headset"),
        array("id"=>"headset_mic","icone" => "headset_mic"),
        array("id"=>"healing","icone" => "healing"),
        array("id"=>"hearing","icone" => "hearing"),
        array("id"=>"help","icone" => "help"),
        array("id"=>"help_outline","icone" => "help_outline"),
        array("id"=>"high_quality","icone" => "high_quality"),
        array("id"=>"highlight_off","icone" => "highlight_off"),
        array("id"=>"history","icone" => "history"),
        array("id"=>"home","icone" => "home"),
        array("id"=>"hotel","icone" => "hotel"),
        array("id"=>"hourglass_empty","icone" => "hourglass_empty"),
        array("id"=>"hourglass_full","icone" => "hourglass_full"),
        array("id"=>"http","icone" => "http"),
        array("id"=>"https","icone" => "https"),
        array("id"=>"image","icone" => "image"),
        array("id"=>"image_aspect_ratio","icone" => "image_aspect_ratio"),
        array("id"=>"import_export","icone" => "import_export"),
        array("id"=>"inbox","icone" => "inbox"),
        array("id"=>"indeterminate_check_box","icone" => "indeterminate_check_box"),
        array("id"=>"info","icone" => "info"),
        array("id"=>"info_outline","icone" => "info_outline"),
        array("id"=>"input","icone" => "input"),
        array("id"=>"insert_chart","icone" => "insert_chart"),
        array("id"=>"insert_comment","icone" => "insert_comment"),
        array("id"=>"insert_drive_file","icone" => "insert_drive_file"),
        array("id"=>"insert_emoticon","icone" => "insert_emoticon"),
        array("id"=>"insert_invitation","icone" => "insert_invitation"),
        array("id"=>"insert_link","icone" => "insert_link"),
        array("id"=>"insert_photo","icone" => "insert_photo"),
        array("id"=>"invert_colors","icone" => "invert_colors"),
        array("id"=>"invert_colors_off","icone" => "invert_colors_off"),
        array("id"=>"iso","icone" => "iso"),
        array("id"=>"keyboard","icone" => "keyboard"),
        array("id"=>"keyboard_arrow_down","icone" => "keyboard_arrow_down"),
        array("id"=>"keyboard_arrow_left","icone" => "keyboard_arrow_left"),
        array("id"=>"keyboard_arrow_right","icone" => "keyboard_arrow_right"),
        array("id"=>"keyboard_arrow_up","icone" => "keyboard_arrow_up"),
        array("id"=>"keyboard_backspace","icone" => "keyboard_backspace"),
        array("id"=>"keyboard_capslock","icone" => "keyboard_capslock"),
        array("id"=>"keyboard_hide","icone" => "keyboard_hide"),
        array("id"=>"keyboard_return","icone" => "keyboard_return"),
        array("id"=>"keyboard_tab","icone" => "keyboard_tab"),
        array("id"=>"keyboard_voice","icone" => "keyboard_voice"),
        array("id"=>"label","icone" => "label"),
        array("id"=>"label_outline","icone" => "label_outline"),
        array("id"=>"landscape","icone" => "landscape"),
        array("id"=>"language","icone" => "language"),
        array("id"=>"laptop","icone" => "laptop"),
        array("id"=>"laptop_chromebook","icone" => "laptop_chromebook"),
        array("id"=>"laptop_mac","icone" => "laptop_mac"),
        array("id"=>"laptop_windows","icone" => "laptop_windows"),
        array("id"=>"launch","icone" => "launch"),
        array("id"=>"layers","icone" => "layers"),
        array("id"=>"layers_clear","icone" => "layers_clear"),
        array("id"=>"leak_add","icone" => "leak_add"),
        array("id"=>"leak_remove","icone" => "leak_remove"),
        array("id"=>"lens","icone" => "lens"),
        array("id"=>"library_add","icone" => "library_add"),
        array("id"=>"library_books","icone" => "library_books"),
        array("id"=>"library_music","icone" => "library_music"),
        array("id"=>"link","icone" => "link"),
        array("id"=>"list","icone" => "list"),
        array("id"=>"live_help","icone" => "live_help"),
        array("id"=>"live_tv","icone" => "live_tv"),
        array("id"=>"local_activity","icone" => "local_activity"),
        array("id"=>"local_airport","icone" => "local_airport"),
        array("id"=>"local_atm","icone" => "local_atm"),
        array("id"=>"local_bar","icone" => "local_bar"),
        array("id"=>"local_cafe","icone" => "local_cafe"),
        array("id"=>"local_car_wash","icone" => "local_car_wash"),
        array("id"=>"local_convenience_store","icone" => "local_convenience_store"),
        array("id"=>"local_dining","icone" => "local_dining"),
        array("id"=>"local_drink","icone" => "local_drink"),
        array("id"=>"local_florist","icone" => "local_florist"),
        array("id"=>"local_gas_station","icone" => "local_gas_station"),
        array("id"=>"local_grocery_store","icone" => "local_grocery_store"),
        array("id"=>"local_hospital","icone" => "local_hospital"),
        array("id"=>"local_hotel","icone" => "local_hotel"),
        array("id"=>"local_laundry_service","icone" => "local_laundry_service"),
        array("id"=>"local_library","icone" => "local_library"),
        array("id"=>"local_mall","icone" => "local_mall"),

       array("id"=>"local_movies","icone" => "local_movies"),
        array("id"=>"local_offer","icone" => "local_offer"),
        array("id"=>"local_parking","icone" => "local_parking"),
        array("id"=>"local_pharmacy","icone" => "local_pharmacy"),
        array("id"=>"local_phone","icone" => "local_phone"),
        array("id"=>"local_pizza","icone" => "local_pizza"),
        array("id"=>"local_play","icone" => "local_play"),
        array("id"=>"local_post_office","icone" => "local_post_office"),
        array("id"=>"local_printshop","icone" => "local_printshop"),
        array("id"=>"local_see","icone" => "local_see"),
        array("id"=>"local_shipping","icone" => "local_shipping"),
        array("id"=>"local_taxi","icone" => "local_taxi"),
        array("id"=>"location_city","icone" => "location_city"),
        array("id"=>"location_disabled","icone" => "location_disabled"),
        array("id"=>"location_off","icone" => "location_off"),
        array("id"=>"location_on","icone" => "location_on"),
        array("id"=>"location_searching","icone" => "location_searching"),
        array("id"=>"lock","icone" => "lock"),
        array("id"=>"lock_open","icone" => "lock_open"),
        array("id"=>"lock_outline","icone" => "lock_outline"),
        array("id"=>"looks","icone" => "looks"),
        array("id"=>"looks_3","icone" => "looks_3"),
        array("id"=>"looks_4","icone" => "looks_4"),
        array("id"=>"looks_5","icone" => "looks_5"),
        array("id"=>"looks_6","icone" => "looks_6"),
        array("id"=>"looks_one","icone" => "looks_one"),
       array("id"=>"looks_two","icone" => "looks_two"),
        array("id"=>"loop","icone" => "loop"),
        array("id"=>"loupe","icone" => "loupe"),
        array("id"=>"loyalty","icone" => "loyalty"),
        array("id"=>"mail","icone" => "mail"),
        array("id"=>"map","icone" => "map"),
        array("id"=>"markunread","icone" => "markunread"),
        array("id"=>"markunread_mailbox","icone" => "markunread_mailbox"),
        array("id"=>"memory","icone" => "memory"),
        array("id"=>"menu","icone" => "menu"),
        array("id"=>"merge_type","icone" => "merge_type"),
        array("id"=>"message","icone" => "message"),
        array("id"=>"mic","icone" => "mic"),
        array("id"=>"mic_none","icone" => "mic_none"),
        array("id"=>"mic_off","icone" => "mic_off"),
        array("id"=>"mms","icone" => "mms"),
        array("id"=>"mode_comment","icone" => "mode_comment"),
        array("id"=>"mode_edit","icone" => "mode_edit"),
        array("id"=>"money_off","icone" => "money_off"),
        array("id"=>"monochrome_photos","icone" => "monochrome_photos"),
        array("id"=>"mood","icone" => "mood"),
        array("id"=>"mood_bad","icone" => "mood_bad"),
        array("id"=>"more","icone" => "more"),
        array("id"=>"more_horiz","icone" => "more_horiz"),
        array("id"=>"more_vert","icone" => "more_vert"),
        array("id"=>"mouse","icone" => "mouse"),
        array("id"=>"movie","icone" => "movie"),
        array("id"=>"movie_creation","icone" => "movie_creation"),
        array("id"=>"music_note","icone" => "music_note"),
        array("id"=>"my_location","icone" => "my_location"),
        array("id"=>"nature","icone" => "nature"),
        array("id"=>"nature_people","icone" => "nature_people"),
        array("id"=>"navigate_before","icone" => "navigate_before"),
        array("id"=>"navigate_next","icone" => "navigate_next"),
        array("id"=>"navigation","icone" => "navigation"),
        array("id"=>"network_cell","icone" => "network_cell"),
        array("id"=>"network_locked","icone" => "network_locked"),
        array("id"=>"network_wifi","icone" => "network_wifi"),
        array("id"=>"new_releases","icone" => "new_releases"),
        array("id"=>"nfc","icone" => "nfc"),
        array("id"=>"no_sim","icone" => "no_sim"),
        array("id"=>"not_interested","icone" => "not_interested"),
        array("id"=>"note_add","icone" => "note_add"),
        array("id"=>"notifications","icone" => "notifications"),
        array("id"=>"notifications_active","icone" => "notifications_active"),
        array("id"=>"notifications_none","icone" => "notifications_none"),
        array("id"=>"notifications_off","icone" => "notifications_off"),
        array("id"=>"notifications_paused","icone" => "notifications_paused"),
        array("id"=>"offline_pin","icone" => "offline_pin"),
        array("id"=>"ondemand_video","icone" => "ondemand_video"),
        array("id"=>"open_in_browser","icone" => "open_in_browser"),
        array("id"=>"open_in_new","icone" => "open_in_new"),
        array("id"=>"open_with","icone" => "open_with"),
        array("id"=>"pages","icone" => "pages"),
        array("id"=>"pageview","icone" => "pageview"),
        array("id"=>"palette","icone" => "palette"),
        array("id"=>"panorama","icone" => "panorama"),
        array("id"=>"panorama_fish_eye","icone" => "panorama_fish_eye"),
        array("id"=>"panorama_horizontal","icone" => "panorama_horizontal"),
        array("id"=>"panorama_vertical","icone" => "panorama_vertical"),
       array("id"=>"panorama_wide_angle","icone" => "panorama_wide_angle"),
        array("id"=>"party_mode","icone" => "party_mode"),
        array("id"=>"pause","icone" => "pause"),
        array("id"=>"pause_circle_filled","icone" => "pause_circle_filled"),
        array("id"=>"pause_circle_outline","icone" => "pause_circle_outline"),
        array("id"=>"payment","icone" => "payment"),
        array("id"=>"people","icone" => "people"),
        array("id"=>"people_outline","icone" => "people_outline"),
        array("id"=>"perm_camera_mic","icone" => "perm_camera_mic"),
        array("id"=>"perm_contact_calendar","icone" => "perm_contact_calendar"),
        array("id"=>"perm_data_setting","icone" => "perm_data_setting"),
        array("id"=>"perm_device_information","icone" => "perm_device_information"),
        array("id"=>"perm_identity","icone" => "perm_identity"),
        array("id"=>"perm_media","icone" => "perm_media"),
        array("id"=>"perm_phone_msg","icone" => "perm_phone_msg"),
        array("id"=>"perm_scan_wifi","icone" => "perm_scan_wifi"),
        array("id"=>"person","icone" => "person"),
        array("id"=>"person_add","icone" => "person_add"),
        array("id"=>"person_outline","icone" => "person_outline"),
        array("id"=>"person_pin","icone" => "person_pin"),
        array("id"=>"personal_video","icone" => "personal_video"),
        array("id"=>"phone","icone" => "phone"),
        array("id"=>"phone_android","icone" => "phone_android"),
        array("id"=>"phone_bluetooth_speaker","icone" => "phone_bluetooth_speaker"),
        array("id"=>"phone_forwarded","icone" => "phone_forwarded"),
        array("id"=>"phone_in_talk","icone" => "phone_in_talk"),
        array("id"=>"phone_iphone","icone" => "phone_iphone"),
        array("id"=>"phone_locked","icone" => "phone_locked"),
        array("id"=>"phone_missed","icone" => "phone_missed"),
        array("id"=>"phone_paused","icone" => "phone_paused"),
        array("id"=>"phonelink","icone" => "phonelink"),
        array("id"=>"phonelink_erase","icone" => "phonelink_erase"),
        array("id"=>"phonelink_lock","icone" => "phonelink_lock"),
        array("id"=>"phonelink_off","icone" => "phonelink_off"),
        array("id"=>"phonelink_ring","icone" => "phonelink_ring"),
        array("id"=>"phonelink_setup","icone" => "phonelink_setup"),

       array("id"=>"photo","icone" => "photo"),
        array("id"=>"photo_album","icone" => "photo_album"),
        array("id"=>"photo_camera","icone" => "photo_camera"),
        array("id"=>"photo_library","icone" => "photo_library"),
        array("id"=>"photo_size_select_actual","icone" => "photo_size_select_actual"),
        array("id"=>"photo_size_select_large","icone" => "photo_size_select_large"),
        array("id"=>"photo_size_select_small","icone" => "photo_size_select_small"),
        array("id"=>"picture_as_pdf","icone" => "picture_as_pdf"),
        array("id"=>"picture_in_picture","icone" => "picture_in_picture"),
        array("id"=>"pin_drop","icone" => "pin_drop"),
        array("id"=>"place","icone" => "place"),
        array("id"=>"play_arrow","icone" => "play_arrow"),
        array("id"=>"play_circle_filled","icone" => "play_circle_filled"),
        array("id"=>"play_circle_outline","icone" => "play_circle_outline"),
        array("id"=>"play_for_work","icone" => "play_for_work"),
        array("id"=>"playlist_add","icone" => "playlist_add"),
        array("id"=>"plus_one","icone" => "plus_one"),
        array("id"=>"poll","icone" => "poll"),
        array("id"=>"polymer","icone" => "polymer"),
        array("id"=>"portable_wifi_off","icone" => "portable_wifi_off"),
        array("id"=>"portrait","icone" => "portrait"),
        array("id"=>"power","icone" => "power"),
        array("id"=>"power_input","icone" => "power_input"),
        array("id"=>"power_settings_new","icone" => "power_settings_new"),
        array("id"=>"present_to_all","icone" => "present_to_all"),
        array("id"=>"print","icone" => "print"),

       array("id"=>"public","icone" => "public"),
        array("id"=>"publish","icone" => "publish"),
        array("id"=>"query_builder","icone" => "query_builder"),
        array("id"=>"question_answer","icone" => "question_answer"),
        array("id"=>"queue","icone" => "queue"),
        array("id"=>"queue_music","icone" => "queue_music"),
        array("id"=>"radio","icone" => "radio"),
        array("id"=>"radio_button_checked","icone" => "radio_button_checked"),
        array("id"=>"radio_button_unchecked","icone" => "radio_button_unchecked"),
        array("id"=>"rate_review","icone" => "rate_review"),
        array("id"=>"receipt","icone" => "receipt"),
        array("id"=>"recent_actors","icone" => "recent_actors"),
        array("id"=>"redeem","icone" => "redeem"),
        array("id"=>"redo","icone" => "redo"),
        array("id"=>"refresh","icone" => "refresh"),
        array("id"=>"remove","icone" => "remove"),

       array("id"=>"remove_circle","icone" => "remove_circle"),
        array("id"=>"remove_circle_outline","icone" => "remove_circle_outline"),
        array("id"=>"remove_red_eye","icone" => "remove_red_eye"),
        array("id"=>"reorder","icone" => "reorder"),
        array("id"=>"repeat","icone" => "repeat"),
        array("id"=>"repeat_one","icone" => "repeat_one"),
        array("id"=>"replay","icone" => "replay"),
        array("id"=>"replay_10","icone" => "replay_10"),
        array("id"=>"replay_30","icone" => "replay_30"),
        array("id"=>"replay_5","icone" => "replay_5"),
        array("id"=>"reply","icone" => "reply"),
        array("id"=>"reply_all","icone" => "reply_all"),
        array("id"=>"report","icone" => "report"),
        array("id"=>"report_problem","icone" => "report_problem"),
        array("id"=>"restaurant_menu","icone" => "restaurant_menu"),
        array("id"=>"restore","icone" => "restore"),

       array("id"=>"ring_volume","icone" => "ring_volume"),
        array("id"=>"room","icone" => "room"),
        array("id"=>"rotate_90_degrees_ccw","icone" => "rotate_90_degrees_ccw"),
        array("id"=>"rotate_left","icone" => "rotate_left"),
        array("id"=>"rotate_right","icone" => "rotate_right"),
        array("id"=>"router","icone" => "router"),
        array("id"=>"satellite","icone" => "satellite"),
        array("id"=>"save","icone" => "save"),
        array("id"=>"scanner","icone" => "scanner"),
        array("id"=>"schedule","icone" => "schedule"),
        array("id"=>"school","icone" => "school"),
        array("id"=>"screen_lock_landscape","icone" => "screen_lock_landscape"),
        array("id"=>"screen_lock_portrait","icone" => "screen_lock_portrait"),
        array("id"=>"screen_lock_rotation","icone" => "screen_lock_rotation"),
        array("id"=>"screen_rotation","icone" => "screen_rotation"),
        array("id"=>"sd_card","icone" => "sd_card"),
        array("id"=>"sd_storage","icone" => "sd_storage"),
        array("id"=>"search","icone" => "search"),
        array("id"=>"security","icone" => "security"),
        array("id"=>"select_all","icone" => "select_all"),
        array("id"=>"send","icone" => "send"),
        array("id"=>"settings","icone" => "settings"),
        array("id"=>"settings_applications","icone" => "settings_applications"),

       array("id"=>"settings_backup_restore","icone" => "settings_backup_restore"),
        array("id"=>"settings_bluetooth","icone" => "settings_bluetooth"),
        array("id"=>"settings_brightness","icone" => "settings_brightness"),
        array("id"=>"settings_cell","icone" => "settings_cell"),
        array("id"=>"settings_ethernet","icone" => "settings_ethernet"),
        array("id"=>"settings_input_antenna","icone" => "settings_input_antenna"),
        array("id"=>"settings_input_component","icone" => "settings_input_component"),
        array("id"=>"settings_input_composite","icone" => "settings_input_composite"),
        array("id"=>"settings_input_hdmi","icone" => "settings_input_hdmi"),
        array("id"=>"settings_input_svideo","icone" => "settings_input_svideo"),
        array("id"=>"settings_overscan","icone" => "settings_overscan"),
        array("id"=>"settings_phone","icone" => "settings_phone"),
        array("id"=>"settings_power","icone" => "settings_power"),

       array("id"=>"settings_remote","icone" => "settings_remote"),
        array("id"=>"settings_system_daydream","icone" => "settings_system_daydream"),
        array("id"=>"settings_voice","icone" => "settings_voice"),
        array("id"=>"share","icone" => "share"),
        array("id"=>"shop","icone" => "shop"),
        array("id"=>"shop_two","icone" => "shop_two"),
        array("id"=>"shopping_basket","icone" => "shopping_basket"),
        array("id"=>"shopping_cart","icone" => "shopping_cart"),
        array("id"=>"shuffle","icone" => "shuffle"),
        array("id"=>"signal_cellular_4_bar","icone" => "signal_cellular_4_bar"),
        array("id"=>"signal_cellular_connected_no_inter","icone" => "signal_cellular_connected_no_internet_4_bar"),
        array("id"=>"signal_cellular_no_sim","icone" => "signal_cellular_no_sim"),
        array("id"=>"signal_cellular_null","icone" => "signal_cellular_null"),
        array("id"=>"signal_cellular_off","icone" => "signal_cellular_off"),
        array("id"=>"signal_wifi_4_bar","icone" => "signal_wifi_4_bar"),
        array("id"=>"signal_wifi_4_bar_lock","icone" => "signal_wifi_4_bar_lock"),

       array("id"=>"signal_wifi_off","icone" => "signal_wifi_off"),
        array("id"=>"sim_card","icone" => "sim_card"),
        array("id"=>"sim_card_alert","icone" => "sim_card_alert"),
        array("id"=>"skip_next","icone" => "skip_next"),
        array("id"=>"skip_previous","icone" => "skip_previous"),
        array("id"=>"slideshow","icone" => "slideshow"),
        array("id"=>"smartphone","icone" => "smartphone"),
        array("id"=>"sms","icone" => "sms"),
        array("id"=>"sms_failed","icone" => "sms_failed"),
        array("id"=>"snooze","icone" => "snooze"),
        array("id"=>"sort","icone" => "sort"),
        array("id"=>"sort_by_alpha","icone" => "sort_by_alpha"),
        array("id"=>"space_bar","icone" => "space_bar"),
        array("id"=>"speaker","icone" => "speaker"),
        array("id"=>"speaker_group","icone" => "speaker_group"),
        array("id"=>"speaker_notes","icone" => "speaker_notes"),
        array("id"=>"speaker_phone","icone" => "speaker_phone"),
        array("id"=>"spellcheck","icone" => "spellcheck"),
        array("id"=>"star","icone" => "star"),

       array("id"=>"star_border","icone" => "star_border"),
        array("id"=>"star_half","icone" => "star_half"),
        array("id"=>"stars","icone" => "stars"),
        array("id"=>"stay_current_landscape","icone" => "stay_current_landscape"),
        array("id"=>"stay_current_portrait","icone" => "stay_current_portrait"),
        array("id"=>"stay_primary_landscape","icone" => "stay_primary_landscape"),
        array("id"=>"stay_primary_portrait","icone" => "stay_primary_portrait"),
        array("id"=>"stop","icone" => "stop"),
        array("id"=>"storage","icone" => "storage"),
        array("id"=>"store","icone" => "store"),
        array("id"=>"store_mall_directory","icone" => "store_mall_directory"),
        array("id"=>"straighten","icone" => "straighten"),
        array("id"=>"strikethrough_s","icone" => "strikethrough_s"),
        array("id"=>"style","icone" => "style"),
        array("id"=>"subject","icone" => "subject"),
        array("id"=>"subtitles","icone" => "subtitles"),
        array("id"=>"supervisor_account","icone" => "supervisor_account"),
        array("id"=>"surround_sound","icone" => "surround_sound"),
        array("id"=>"swap_calls","icone" => "swap_calls"),

       array("id"=>"swap_horiz","icone" => "swap_horiz"),
        array("id"=>"swap_vert","icone" => "swap_vert"),
        array("id"=>"swap_vertical_circle","icone" => "swap_vertical_circle"),
        array("id"=>"switch_camera","icone" => "switch_camera"),
        array("id"=>"switch_video","icone" => "switch_video"),
        array("id"=>"sync","icone" => "sync"),
        array("id"=>"sync_disabled","icone" => "sync_disabled"),
        array("id"=>"sync_problem","icone" => "sync_problem"),
        array("id"=>"system_update","icone" => "system_update"),
        array("id"=>"system_update_alt","icone" => "system_update_alt"),
        array("id"=>"tab","icone" => "tab"),
        array("id"=>"tab_unselected","icone" => "tab_unselected"),
        array("id"=>"tablet","icone" => "tablet"),
        array("id"=>"tablet_android","icone" => "tablet_android"),
        array("id"=>"tablet_mac","icone" => "tablet_mac"),
        array("id"=>"tag_faces","icone" => "tag_faces"),
        array("id"=>"tap_and_play","icone" => "tap_and_play"),
        array("id"=>"terrain","icone" => "terrain"),
        array("id"=>"text_format","icone" => "text_format"),
        array("id"=>"textsms","icone" => "textsms"),
        array("id"=>"texture","icone" => "texture"),
        array("id"=>"theaters","icone" => "theaters"),
        array("id"=>"thumb_down","icone" => "thumb_down"),
        array("id"=>"thumb_up","icone" => "thumb_up"),
        array("id"=>"thumbs_up_down","icone" => "thumbs_up_down"),
        array("id"=>"time_to_leave","icone" => "time_to_leave"),
        array("id"=>"timelapse","icone" => "timelapse"),
        array("id"=>"timer","icone" => "timer"),
        array("id"=>"timer_10","icone" => "timer_10"),
        array("id"=>"timer_3","icone" => "timer_3"),
        array("id"=>"timer_off","icone" => "timer_off"),
        array("id"=>"toc","icone" => "toc"),
        array("id"=>"today","icone" => "today"),
        array("id"=>"toll","icone" => "toll"),
        array("id"=>"tonality","icone" => "tonality"),
        array("id"=>"toys","icone" => "toys"),
        array("id"=>"track_changes","icone" => "track_changes"),
        array("id"=>"traffic","icone" => "traffic"),
        array("id"=>"transform","icone" => "transform"),
        array("id"=>"translate","icone" => "translate"),
        array("id"=>"trending_down","icone" => "trending_down"),
        array("id"=>"trending_flat","icone" => "trending_flat"),
        array("id"=>"trending_up","icone" => "trending_up"),
        array("id"=>"tune","icone" => "tune"),
        array("id"=>"turned_in","icone" => "turned_in"),
        array("id"=>"turned_in_not","icone" => "turned_in_not"),
        array("id"=>"tv","icone" => "tv"),
        array("id"=>"undo","icone" => "undo"),
        array("id"=>"unfold_less","icone" => "unfold_less"),
        array("id"=>"unfold_more","icone" => "unfold_more"),
        array("id"=>"usb","icone" => "usb"),
        array("id"=>"verified_user","icone" => "verified_user"),
        array("id"=>"vertical_align_bottom","icone" => "vertical_align_bottom"),
        array("id"=>"vertical_align_center","icone" => "vertical_align_center"),
        array("id"=>"vertical_align_top","icone" => "vertical_align_top"),
        array("id"=>"vibration","icone" => "vibration"),
        array("id"=>"video_library","icone" => "video_library"),
        array("id"=>"videocam","icone" => "videocam"),
        array("id"=>"videocam_off","icone" => "videocam_off"),
        array("id"=>"view_agenda","icone" => "view_agenda"),
        array("id"=>"view_array","icone" => "view_array"),
        array("id"=>"view_carousel","icone" => "view_carousel"),
        array("id"=>"view_column","icone" => "view_column"),
        array("id"=>"view_comfy","icone" => "view_comfy"),
        array("id"=>"view_compact","icone" => "view_compact"),
        array("id"=>"view_day","icone" => "view_day"),
        array("id"=>"view_headline","icone" => "view_headline"),
        array("id"=>"view_list","icone" => "view_list"),
        array("id"=>"view_module","icone" => "view_module"),
        array("id"=>"view_quilt","icone" => "view_quilt"),
        array("id"=>"view_stream","icone" => "view_stream"),
        array("id"=>"view_week","icone" => "view_week"),
        array("id"=>"vignette","icone" => "vignette"),
        array("id"=>"visibility","icone" => "visibility"),
        array("id"=>"visibility_off","icone" => "visibility_off"),
        array("id"=>"voice_chat","icone" => "voice_chat"),
        array("id"=>"voicemail","icone" => "voicemail"),
        array("id"=>"volume_down","icone" => "volume_down"),
        array("id"=>"volume_mute","icone" => "volume_mute"),
        array("id"=>"volume_off","icone" => "volume_off"),
        array("id"=>"volume_up","icone" => "volume_up"),
        array("id"=>"vpn_key","icone" => "vpn_key"),
        array("id"=>"vpn_lock","icone" => "vpn_lock"),
        array("id"=>"wallpaper","icone" => "wallpaper"),
        array("id"=>"warning","icone" => "warning"),
        array("id"=>"watch","icone" => "watch"),
        array("id"=>"wb_auto","icone" => "wb_auto"),
        array("id"=>"wb_cloudy","icone" => "wb_cloudy"),
        array("id"=>"wb_incandescent","icone" => "wb_incandescent"),
        array("id"=>"wb_iridescent","icone" => "wb_iridescent"),
        array("id"=>"wb_sunny","icone" => "wb_sunny"),
        array("id"=>"wc","icone" => "wc"),
        array("id"=>"web","icone" => "web"),
        array("id"=>"whatshot","icone" => "whatshot"),
        array("id"=>"widgets","icone" => "widgets"),
        array("id"=>"wifi","icone" => "wifi"),
        array("id"=>"wifi_lock","icone" => "wifi_lock"),
        array("id"=>"wifi_tethering","icone" => "wifi_tethering"),
        array("id"=>"work","icone" => "work"),
       array("id"=>"wrap_text","icone" => "wrap_text"),
       array("id"=>"youtube_searched_for","icone" => "youtube_searched_for"),
       array("id"=>"zoom_in","icone" => "zoom_in"),
       array("id"=>"zoom_out","icone" => "zoom_out"),
    );
          
           if(!empty($id)){
                $programa_dados =$programa->listar_programa($join, "1", "id='$id'", $offset, $orderby);
                $programa_dados = $programa_dados[0]; 
                $comando="/".__CLASS__."/alterar/";
                $nome_form="Alterar Programa";
            }             

            $form = new FormularioHelper($nome_form,"col-md-12" ,$comando,"POST","people");
            $inputs.= $form->Input("hidden", "id", null, $id, $Required, null, $disable);
            $inputs.= $form->select("Filial","id_filial", "col-md-2", $filial->listar_Filial(NULL,NULL,"Filial.id_status<>'99'",NULL,' Filial.id DESC',NULL),"nome_fantasia",$programa_dados["id_filial"]);
            $inputs.= $form->select("Pai","id_pai", "col-md-3",$listar_programa,"descricao",$programa_dados["id_pai"]);
            $inputs.= $form->Input("text", "descricao", "col-md-4", $programa_dados["descricao"], $Required, "Descrição", $disable);
            $inputs.= $form->select("Tipo","tipo", "col-md-3", array(array("id"=>"PAI","descricao"=>"PAI"),array("id"=>"FILHO","descricao"=>"FILHO"),array("id"=>"FLUXO","descricao"=>"FLUXO"),array("id"=>"Relatorio","descricao"=>"Relatorio")),  "descricao",$programa_dados["tipo"]);
            $inputs.= $form->Input("text", "comando", "col-md-3", $programa_dados["comando"], $Required, "Comando", $disable);
            $inputs.= $form->Input("text", "versao", "col-md-1", $programa_dados["versao"], $Required, "Versao", $disable);
            $inputs.= $form->Input("color", "Cor", "col-md-1", $programa_dados["cor"], $Required, "cor", $disable);
            $inputs.= $form->Input("text", "Posição", "col-md-1", $programa_dados["ordem"], $Required, "ordem", $disable);
         //   $inputs.= $form->select_imagem("Icone","icone", "col-md-3",$icone, "icone",$disable);
           $inputs.= $form->select("Icone","icone", "col-md-3",$icone,"icone",$programa_dados["icone"]);
            $inputs.= $form->select("Status","id_status", "col-md-3", $status->listar_Status(NULL,NULL,"id_status<>99 AND tabela='Geral'",NULL,' Status.id ASC',NULL),"descricao",$programa_dados["id_status"]);
            $inputs.= $form->Button("btn btn-md btn-rose ","Salvar");
            $form->card(__CLASS__,$inputs,"col-md-12",$comando,"POST","api");
        }else{
           $this->view('error_permisao');
        }   
    }

 public function incluir(){    
        $this->acesso_restrito();
        $acesso = new AcessoHelper(); 
        $logs = new LogsModel();
        $comando='/Programa/incluir/';           
       if($acesso->acesso_valida($comando)==true){
            $programa = new ProgramaModel();      
            $id=$programa->cadastrar_programa( 
                array(
                    'id_filial'=>$_POST['id_filial'],
                    'id_pai'=>$_POST['id_pai'],
                    'descricao'=>$_POST['descricao'],
                    'tipo'=>$_POST['tipo'],
                    'cor'=>$_POST['cor'],
                    'comando'=>$_POST['comando'],
                    'versao'=>$_POST['versao'],
                    'icone'=>$_POST['icone'],
                    'id_status'=>$_POST['id_status'],
                   'data_lancamento'=>  date("Y-m-d H:i:s"),
                )
            );  
            $logs->cadastrar_logs($comando,$id);//Gera Logs
            $redirect = new RedirectHelper();
            $redirect->goToUrl('/Programa/admin_listar/');    
        }else{
            $this->view('error_permisao');
        }
    }

 public function alterar(){    
        $this->acesso_restrito();
        $acesso = new AcessoHelper(); 
        $logs = new LogsModel();
        $comando='/Programa/alterar/';
        if($acesso->acesso_valida($comando)==true){
            $id = $_POST['id'];
            $programa = new ProgramaModel();      
           $programa->alterar_programa(
                array(
                   'id_filial'=>$_POST['id_filial'],
                    'id_pai'=>$_POST['id_pai'],
                    'descricao'=>$_POST['descricao'],
                    'tipo'=>$_POST['tipo'],
                    'cor'=>$_POST['cor'],
                    'comando'=>$_POST['comando'],
                    'versao'=>$_POST['versao'],
                    'icone'=>$_POST['icone'],
                    'id_status'=>$_POST['id_status'],
                ),'id='.$id
            );  
            $logs->cadastrar_logs($comando,$id);//Gera Logs
            $redirect = new RedirectHelper();
            $redirect->goToUrl('/Programa/admin_listar/');    
        }else{
            $this->view('error_permisao');
        }
    }

public function excluir(){    
        $this->acesso_restrito();
        $acesso = new AcessoHelper(); 
        $logs = new LogsModel();
        $comando='/Programa/excluir/';
        if($acesso->acesso_valida($comando)==true){
            $id = $this->getParams('id');
            $programa = new ProgramaModel();      
            $programa->excluir_programa( array( 'id_status'=>'99' ),'id='.$id );  
            $logs->cadastrar_logs($comando,$id);//Gera Logs
            $redirect = new RedirectHelper();
            $redirect->goToUrl('/Programa/admin_listar/');    
        }else{
            $this->view('error_permisao');
        }
    } 
 } ?> 